rubyforgood/homeward-tails

app/controllers/adoptable_pets_controller.rb
These 2 queries have N+1s
`AdopterApplication Load (0.1ms)  SELECT "adopter_applications".* FROM "adopter_applications" WHERE "adopter_applications"."pet_id" = $1  [["pet_id", 8]]`
`ActiveStorage::Attachment Exists? (0.2ms)  SELECT 1 AS one FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 9], ["record_type", "Pet"], ["name", "images"], ["LIMIT", 1]]`
The latter is using a `has_many_attached`, so we have to name the eager load slightly differently https://blog.saeloun.com/2020/03/06/eagerload-active-storage-models/
No issue required per @edwinthinks
=> Fix n+1 on /adoptable_pets

app/views/static_pages/home.html.erb, test/integration/static_pages_test.rb
Not sure why it's broken without this change, but this is the error we're seeing
```
<We rescue pets in Baja, Mexico and rehome them with adopters in
Canada and America> expected but was
<We rescue pets in Baja, Mexico and rehome them with adopters in
Canada and America>..
```
=> Fix static_pages_test

.github/workflows/rubyonrails.yml
This PR runs [`standard`](https://github.com/standardrb/standard) as part of our GitHub CI
https://github.com/rubyforgood/pet-rescue/issues/50
=> Add `standard` to CI

.github/workflows/rubyonrails.yml, Gemfile, Gemfile.lock
[Installs `brakeman`](https://brakemanscanner.org/docs/quickstart/) and runs it on CI
If Brakeman detects warnings, it'll exit with a non-zero exit code. This should cause the CI test to fail when necessary.
Closes https://github.com/rubyforgood/pet-rescue/issues/51
=> Install brakeman gem to analyze for security vulnerabilities

app/models/pet.rb, db/migrate/20230729141917_remove_unique_index_on_pet_name.rb, db/schema.rb, test/fixtures/pets.yml
We removed the ActiveRecord validation in https://github.com/rubyforgood/pet-rescue/pull/58 but not the database constraint. This PR removes the DB constraint too.
One consequence is database seeding could fail due to Faker generating the same name.
=> Remove unique index on pet name

app/mailers/match_mailer.rb, app/models/adoption.rb, app/views/match_mailer/checklist_reminder.html.erb, app/views/match_mailer/checklist_reminder.text.erb, test/mailers/match_mailer_test.rb, test/mailers/previews/match_mailer_preview.rb
Send an email to the adopter regarding their Pet's vaccines when an adoption has been made
https://github.com/rubyforgood/pet-rescue/assets/20099646/60857067-7a8f-4e28-9223-42bfd7458860
http://localhost:3000/rails/mailers/match_mailer/checklist_reminder
https://github.com/rubyforgood/pet-rescue/issues/82
This will later be improved upon in https://github.com/rubyforgood/pet-rescue/issues/83
=> Adoption: Add vaccine reminder mailer

app/controllers/registrations_controller.rb, app/views/adoptable_pets/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/layouts/application.html.erb, app/views/static_pages/about_us.html.erb, app/views/static_pages/home.html.erb, config/routes.rb, test/integration/adoptable_pet_show_test.rb, test/integration/adopter_signup_test.rb, test/integration/static_pages_test.rb, test/integration/user_account_test.rb
- Removed account_select route
- Removed the account_select shared partial
- Removed the conditionals that required account type from the new users registration view
- Changed caption and route of Create account links to 'Adopt'. They point to the  new user registration path instead of the account select path
- Removed Staff emails from the send_email method in the registrations controller
=> Removed ability to create staff acount

test/test_helper.rb
Those with a keen eye may have noticed this folder getting bigger & bigger as tests are run: `tmp/storage_fixtures`
In the integration tests `org_pets_test.rb`, there are tests that use these attachment fixtures regarding uploading/deleting images.
What this commit does is clean the files up after all the tests are run, essentially wiping the `storage_fixtures` folder altogether, instead of adding fixture files to that folder indefinitely.
=> Remove fixture files after tests are run

app/controllers/matches_controller.rb, app/models/match.rb, db/migrate/20230729200513_add_organization_id_to_matches.rb, db/schema.rb, db/seeds.rb, test/fixtures/matches.yml, test/models/match_test.rb
I wanted to add `acts_as_tenant(:organization, through: :pet)` to the
Match model, but it looks like `through` is only supported for HABTM
associations and not belongs_to/has_one. This seems to be intentional
design in acts_as_tenant https://github.com/ErwinM/acts_as_tenant/issues/293#issuecomment-1238567771
So I added `organization_id` to `Match`, but a risk of doing that is
when there's a discrepancy between the denormalized tenant_id and the
tenant_id reachable through the object graph. In this case that would be
when `match.organization_id` does not match `match.pet.organization_id`.
My preferred way of dealing with that is adding a composite foreign key
including the tenant_id so that you can use the database to establish and
guarantee "chain of trust" up to the tenant. Here that …
=> Denormalize organization_id onto Match

app/controllers/organization_pets_controller.rb, app/models/pet.rb, app/views/adoptable_pets/index.html.erb, app/views/adoptable_pets/show.html.erb, app/views/organization_pets/_form.html.erb, app/views/organization_pets/show.html.erb, db/migrate/20230730134633_add_birthdate_to_pets.rb, db/migrate/20230730145336_remove_age_from_pets.rb, db/schema.rb, db/seeds.rb, test/fixtures/pets.yml, test/integration/org_pets_test.rb, test/models/match_test.rb, test/models/pet_test.rb
Closes https://github.com/rubyforgood/pet-rescue/issues/90
Currently age is a static form field, so if a month passes in real time, the pet's age stays the same.
Ruby (https://bugs.ruby-lang.org/issues/14877) nor ActiveSupport have a
way to compute the age given a birthday and most answers online are
concerned with human ages which tend to only be in years. ~~Since it seems
like we want to include months, especially if the pet is less than 1
year old, I added a custom function for computing and display that. It
isn't technically accurate because we compute it off the duration from
today and the birthdate, but should be acceptable because birthdates in
the system will typically be approximate anyway.~~
Switched this to use https://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.ht …
=> Add birth_date to Pet and compute age dynamically

Gemfile, Gemfile.lock, test/controllers/checklist_templates_controller_test.rb, test/factories.rb, test/integration/adoptable_pets_index_test.rb, test/integration/adopter_application_test.rb, test/test_helper.rb
This PR introduces [FactoryBot](https://github.com/thoughtbot/factory_bot_rails), which I think we'll want to move towards. I'm keeping the fixtures in the codebase for now because existing tests rely on it but over time hopefully we can replace our usage of fixtures with factories instead.
`test/integration/adopter_application_test.rb` shows a more complicated/usual example of how that may look. I don't think we should have all of our factories in one file as I do here but for now it's kind of convenient.
If this looks good I think we might as well merge it now and just keep it as an ongoing process in the background that we'll gradually replace the tests and hopefully someday soon retire the fixtures!
#126
=> Begin replacing fixtures with FactoryBot

app/controllers/registrations_controller.rb, app/views/devise/registrations/new.html.erb, test/integration/user_account_test.rb
Removed password confirmation on account creation.
According to the [devise docs](https://github.com/heartcombo/devise/wiki/Disable-password-confirmation-during-registration), this changes are enough to remove password confirmation. 
https://github.com/rubyforgood/pet-rescue/issues/91
=> Remove password confirmation on registration

app/controllers/concerns/organization_scopable.rb, test/system/login_test.rb
Adds logic to redirect verified staff to the dashboard so they are brought to management tools directly after login. Any non-verified staff are taking to the adoptable pets section.
N/A
1. Goto the /alta/users/sign_in page
2. Login as staff@alta.com / 123456
3. You should be redirected to the dashboard page.
N/A
=> Update redirection logic after login to goto dashboard if they are verified staff

app/views/devise/sessions/new.html.erb, app/views/layouts/devise.html.erb, config/initializers/devise.rb
This handles the issue in #185 in which we want to inform users when their username/password is incorrect.
#185
=> Show error message when login does not work

app/javascript/controllers/flash_message_controller.js, app/views/layouts/application.html.erb, app/views/layouts/dashboard.html.erb, app/views/layouts/shared/_flash_messages.html.erb
Upgrade flash messages on every layout except the devise. It uses the bootstrap toast element and is triggered by the stimulus controller.
I didn't use the stimulus notifications because bootstrap toasts disappear automatically without any additional JS.
https://github.com/rubyforgood/pet-rescue/assets/96994176/356da918-2da2-45de-abc5-350d66c42cd1
Fixes #186
=> Upgrade flash messages

app/controllers/adopter_profiles_controller.rb, app/models/adopter_profile.rb, app/models/location.rb, db/migrate/20231002150909_change_association_between_location_and_adopter_profile.rb, db/schema.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb, test/factories.rb, test/models/location_test.rb
Fixes #216 
This PR inverts the association between `Location` and `AdopterProfile` models.
Now:
* `AdopterProfile` belongs to `Location`
*  `Location` has one `AdopterProfile`. 
@kasugaijin suggested in the issue that `Location` should use `has_many :adopter_profiles` relation but from my understanding of the codebase the `has_one` relation makes more sense. Please let me know if I'm wrong, I will change it if needed.
=> Invert association between Location and AdopterProfile

app/models/location.rb, app/models/organization.rb, app/views/organizations/home/index.html.erb, db/migrate/20231003094720_remove_location_fields_from_organizations.rb, db/migrate/20231003095748_add_zipcode_to_locations.rb, db/schema.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb, test/factories.rb
https://github.com/rubyforgood/pet-rescue/issues/228
Removing following fields from Organization:
- City
- Country
- Zipcode
Adding following field to Location
- Zipcode
=> 228 remove location columns on organizations table and add zipcode to locations table

Gemfile, Gemfile.lock, test/application_system_test_case.rb
Fixes #203 
* Increased `process_timeout` for the driver to 20s (maybe 10s would work just fine but 20s is safer and doesn't cost us anything)
* I also bumped `city-state` gem to a newer version because it was throwing deprecation warnings all the time
=> Increase process timeout in tests

app/views/layouts/dashboard.html.erb
Fixes #235 
I think flash messages were removed from the dashboard by mistake. This brings them back. 
https://github.com/rubyforgood/pet-rescue/assets/96994176/c188fdf4-3059-4d96-b04b-26cf43136c91
=> Fix flash messages on the dashboard

README.md, app/.all-contributorsrc
[232](https://github.com/rubyforgood/pet-rescue/issues/232)
The AllContributors intstall instructions here: https://allcontributors.org/docs/en/bot/installation 
Step 1: I do not think I am authorized to do so. I can select the Pet Rescue repo to add access for AllContributors, but it says 'Request' so I think someone may have to approve (one of my multiple requests).
Step 2: I do not have the ability to modify these configurations on the repo - someone else might have to do that. 
Step 3: I added the necessary to readme.md and created the required file.
Hopefully someone can advise/authorise what needs to be done to install the bot on the repo.
=> Add All Contributors to repo

app/views/organizations/pets/_form.html.erb, app/views/organizations/pets/index.html.erb
Fixes #229 
I added an application_paused toggle on the form and a button on the dropdown pets index. I also noticed that the delete button does not work, so I fixed it. 
https://github.com/rubyforgood/pet-rescue/assets/96994176/ba3e9c68-ef96-4319-b90d-03c576558aeb
=> Add application paused toggle

app/views/organizations/organization_profiles/_form.html.erb, config/locales/en.yml
[213](https://github.com/rubyforgood/pet-rescue/issues/213)
We added a new gem `bootstrap_form` which makes forms better readable, reducing the need for label and error specific fields. 
As this form was introduced after the gem has been introduced, this was still using the old pattern. This changes with this pr :)
Before: 
Errors:
After (Already upgraded with new locale keys): 
Errors:
=> Apply bootstrap_form to newly added organization_profile form

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/organizations/pets/_form.html.erb
[#244](https://github.com/rubyforgood/pet-rescue/issues/244)
I moved the field hints below inputs for an improved appearance and removed the extra asterisk that remained in sign up page. I also removed the old validation errors in favor of the bootstrap_form validation errors, however it dawned on me that the other forms all still have hardcoded validation error messages. I'm not sure if that warrants a new issue, or how we wanted to handle that. 
For the record, if we want to continue to write our own custom validation error messages, bootstrap_form offers [options for handling validations and errors](https://github.com/bootstrap-ruby/bootstrap_form#validation-and-errors) like disabling automatic inline errors. I just assumed we wanted to let bootstrap_form handle this as well, so please …
=> Fix pets form field hints, asterisk, validations

app/models/organization_profile.rb, app/services/organizations/create_service.rb
…n and profile in create org service.
https://github.com/rubyforgood/pet-rescue/issues/253
This PR adds creation of the Location and Organization profile to the service class that we use to set up a new org from the terminal.
=> Add creation of location and org profile to create org service

app/models/staff_account.rb, app/views/organizations/staff/index.html.erb, config/locales/en.yml
Fixes #266 
Now, the status column on the staff index displays "Invitation sent" if the invitation is sent but not accepted or "Enabled" if the invitation is accepted. 
https://github.com/rubyforgood/pet-rescue/assets/96994176/18dab9c6-fcda-4c68-8e65-f167f4e10cc8
=> Display invitation status on staff index

test/test_helper.rb
Once `default_url_options[:script_name]` was set (e.g. by calling `set_organization` [here](https://github.com/rubyforgood/pet-rescue/blob/main/test/integration/adoptable_pets_index_test.rb#L7)) it was then leaking to other tests. This change ensures that the script_name is cleared after each test so it should fix the majority of flaky tests.
=> Fix flaky tests

app/views/organizations/pets/show.html.erb
[#281](https://github.com/rubyforgood/pet-rescue/issues/281)
Replaced the dropdown button and drop down with an edit button and added a delete button beneath the summary card. I matched the new buttons to the other button the page. If you'd prefer other styling, I can change it.
=> 281: Pets Show Overview Tab make Edit and Delete buttons more visible

app/views/organizations/pets/_form.html.erb, app/views/organizations/pets/show.html.erb
…ng these in the Files tab of Pet show page. Also convert link_to to button_to as the former was not working
https://github.com/rubyforgood/pet-rescue/issues/283
Quick fix to remove image and upload from pets new and edit forms. File uploads will be handled in the Files tab of pets show.
Cleaned up pet form
=> Remove image and file field from pet form

app/controllers/organizations/staff_controller.rb, app/models/staff_account.rb, app/models/user.rb, app/views/layouts/shared/_flash_messages.html.erb, app/views/organizations/staff/index.html.erb, config/locales/devise.en.yml, config/locales/en.yml, config/routes.rb, db/migrate/20231019115817_add_deactivated_at_to_staff_accounts.rb, db/schema.rb, test/integration/organizations/deactivate_activate_staff_test.rb, test/models/staff_account_test.rb
Fixes #169 
This PR implements activating and deactivating staff by staff admin. When staff is deactivated they cannot log in. Staff admin cannot deactivate themself because they are logged out immediately and won't be able to activate themself. 
https://github.com/rubyforgood/pet-rescue/assets/96994176/5a25959a-bace-4ce4-a3a7-79bad7c5015a
=> Activate and deactivate staff

app/controllers/organizations/invitations_controller.rb, app/models/adopter_account.rb, app/models/staff_account.rb, db/migrate/20231023113924_remove_default_values.rb, db/schema.rb, test/integration/organizations/invite_staff_test.rb
Fixes #297 
I removed default values from: 
- adopter_accounts.user_id,
- staff_accounts.organization_id,
- staff_accounts.user_id
=> Remove default values from foreign keys

app/models/organization_profile.rb, config/environments/test.rb, test/factories.rb, test/integration/adoptable_pet_show_test.rb, test/integration/organizations/invite_staff_test.rb, test/models/checklist_assignment_test.rb, test/models/organization_profile_test.rb, test/system/login_test.rb, test/system/users_test.rb, test/test_helper.rb
This PR addresses some inconsistencies in our test suite to enhance its stability and the overall developer experience. 
Here's a summary of the improvements made:
1. Changed the `setup` function in test_helper.rb to ensure it is called before the `setup` block in individual test files.
2. Resolved issues of Organizations generated with factories having duplicate slugs.
3. Clarified interconnected associations in factories to ensure consistency:
```
match = create(:match)
match.organization == match.pet.organization # => now true
```
4. Resolved issues of Users generated with factories having duplicate emails.
5. Streamlined the behavior of factories with ActsAsTenant:
```
user = create(:user)
user.organization == ActsAsTenant.test_tenant # => true
Organization.count # => 1 (was 2 before …
```
=> Improve tests stability

app/views/layouts/dashboard/_sidebar.html.erb, app/views/nice_partials/_applications.html.erb, app/views/organizations/adoption_application_reviews/_search_results.html.erb, app/views/organizations/pets/index.html.erb, test/integration/adoptable_pet_show_test.rb
Co-authored-by: FionaDL fionadlapham@gmail.com
https://github.com/rubyforgood/pet-rescue/issues/258
1. Added a partial that will render all applications on the pet show page when the tab applications is selected
2. Fixed sidebar styling as it was spilling into the contents of the web page and interfering with the tab navlinks
3. Fixed applicant name at `/adoption_application_reviews`
4. Adds tests for application tab
=> Add Applications list to Pet show

app/models/organization.rb, db/migrate/20231025113121_add_uniq_index_to_organizations_slug.rb, db/schema.rb
Fixes #301 
I added the uniq index to the organizations.slug column.
=> Add uniq index to organization slug

app/controllers/concerns/organization_scopable.rb, test/system/login_test.rb, test/system/users_test.rb
Resolves #305
After successful login, staff are redirected to /pets (pets#index view). The previous behaviour redirected to the organization's dashboard.
=> Modify staff login to redirect to pets#index

app/controllers/organizations/pets_controller.rb, app/models/pet.rb, app/views/organizations/pets/_form.html.erb, test/models/pet_test.rb
[#304](https://github.com/rubyforgood/pet-rescue/issues/304)
Added species select field between sex and breed, updated pet strong params. I also added validates presence of species to the model and to pet test.
=> #304 Allow to set species on pet create/edit form

app/views/layouts/dashboard.html.erb, app/views/organizations/pets/index.html.erb
Removes large margin from dashboard layout. 
It's not perfect. Right around 800px, there is a little bit of overflow that is causing the rightmost icon in the navbar to be cut off (I included a screenshot of the issue so you can see). This is being caused by the table, although I am uncertain what exactly about the table is causing it. 
Desktop: 
Mobile: 
800px weirdness:
=> Remove margin from dashboard layout

app/views/organizations/pets/index.html.erb
[#325](https://github.com/rubyforgood/pet-rescue/issues/325)
Changed pet status column background color to dark gray.
=> Give pet status column more contrast in the pets index table (#325)

Gemfile, Gemfile.lock, app/assets/stylesheets/custom.scss, app/components/avatar_component.rb, app/views/devise/registrations/edit.html.erb, app/views/layouts/dashboard.html.erb, app/views/layouts/shared/_navbar.html.erb, test/system/users_test.rb
Added avatar component so it properly shows avatar wherever we need it. This component includes options for different sizes, avatar source, or displaying initials if no picture is available. It also has different background colors for different initials.
An example of how to use it:
`<%= render AvatarComponent.new(alt: current_user.first_name.first.upcase, src: current_user.avatar) %>`
This component shows a picture if the user has an avatar. If the user has no avatar it shows it's initial with a colored background.
I already added the component to the navbar/dashboard/dropdown.
=> Add avatar component

app/helpers/application_helper.rb, app/views/layouts/dashboard/_sidebar.html.erb
https://github.com/rubyforgood/pet-rescue/issues/199
- Created new helper method to display current `organization.name` or `tenant.name`
- Replaced `<a>` tag with `<p>`in order to display name
https://jam.dev/c/593bece9-2e68-4f2f-8fe1-3f9037d5bbe6
=> Replace sidebar image with current organization name

app/views/layouts/dashboard.html.erb, app/views/organizations/pets/index.html.erb
Reverts rubyforgood/pet-rescue#331
This 'fix' for the dashboard no longer works on the contributor's machine so it's not likely a long-term sustainable fix.
=> Revert "Remove margin from dashboard layout"

db/seeds/01_alta.rb, db/seeds/02_baja.rb
n/a
A quick fix to the seeds to make sure when we are creating the adopter applications that they are scoped to adopter_accounts in the same organization. The current approach will cause some adopter applications in Baja org to belong to adopter accounts in Alta org because it is not limiting the query to just adtoper accounts scoped to Baja. This was found during review of this PR https://github.com/rubyforgood/pet-rescue/pull/338
=> Fix seed file

app/views/layouts/dashboard.html.erb
The dashboard layout was broken on screens wider than 768px:
Now it should be displayed correctly on all screens :)
There are still some issues with the sidebar sometimes, we can fix it separately.
https://github.com/rubyforgood/pet-rescue/assets/16762860/a58bbd5d-b6b1-4fcf-94d4-167c5aed1916
=> Fix layout on wide screens

app/views/layouts/dashboard.html.erb
Reverts rubyforgood/pet-rescue#348
Looks like it still was broken on some browsers (reported here: https://github.com/rubyforgood/pet-rescue/pull/354).
It also messed up some colors.
We need to revisit this.
=> Revert "Fix layout on wide screens"

app/controllers/organizations/pets_controller.rb, app/views/components/dashboard/_page.html.erb, app/views/components/pet_tabs/_tasks.html.erb, app/views/organizations/organization_profiles/_form.html.erb, app/views/organizations/organization_profiles/edit.html.erb, app/views/organizations/pets/_form.html.erb, app/views/organizations/pets/index.html.erb, app/views/organizations/pets/show.html.erb, app/views/organizations/staff/index.html.erb, config/breadcrumbs.rb
N/A
I saw that there were a number of pages that weren't conforming to the theme. This PR addresses a few of them (see below for snapshots). A few main points:
- The layout created wasn't being used in the pets#show page and various others. This use of the shared layout enforces more the styling patterns. 
- Search in pets#index updated to match the inline approach in Geeks Theme
- Included a `sub_header` on the main page layout component
- Coloring adjustments on buttons
I didn't include adjusting the pet#new or staff#new page as I'am not exactly sure the style we want to introduce yet.
The goal of this is to help introduce a more consistent pattern across the application for visual appeal and functionality.
=> Update styling to match theme on various pages

app/views/components/_image_attachment_table.html.erb
Resolves #351 
Improved the photos table by formatting the design of the table and adding links to download the image when clicking on the image or the filename.
=> Improve image table design

app/views/components/_file_attachment_table.html.erb
https://github.com/rubyforgood/pet-rescue/issues/376
Add 'No files attached.' to the Pet File tab if there are no uploads
=> Add 'No files attached.' to the Pet File tab

app/controllers/organizations/pets_controller.rb, app/models/pet.rb, app/views/organizations/pets/_pause_toggle.html.erb, app/views/organizations/pets/index.html.erb, app/views/organizations/pets/update.turbo_stream.erb, test/controllers/organizations/pets_controller_test.rb
Resolves #272 
-Add turbo stream toggle to pause applications on pets page
-Remove previous pause button from dropdown
-Add test for responding to turbo stream only from the pets pages. Ensure proper redirect on pet edit page vs updating the dom via turbo streams on the pets page.
[Screencast from 12-17-2023 09:11:00 AM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/43a7b2fd-dabb-47b5-af38-8b21be0fe399)
=> Add pause application toggle to pets page

app/controllers/organizations/adoption_application_reviews_controller.rb, app/models/adopter_application.rb, app/models/pet.rb, app/views/organizations/adoption_application_reviews/_search_results.html.erb, app/views/organizations/adoption_application_reviews/index.html.erb, app/views/organizations/pets/show.html.erb, app/views/organizations/pets/tabs/_applications.html.erb, test/controllers/organizations/adoption_application_reviews_controller_test.rb
resolves #355
Allow staff to filter adopter applications by pet name, applicant name, and application status.
https://github.com/phonghpham/pet-rescue/assets/9318603/9644ff4f-a82f-4e95-9ddd-46bb8450df46
=> 355 filtering adopter applications

app/models/task.rb, app/views/organizations/pets/tasks/_tasks.html.erb, app/views/organizations/pets/tasks/_tasks_toggle.html.erb
#386 
Added checkbox to toggle completed on tasks
=> complete toggle for tasks

app/controllers/organizations/invitations_controller.rb
https://github.com/rubyforgood/pet-rescue/issues/264
Redirect admin to dashboard after invitation accept
https://github.com/rubyforgood/pet-rescue/assets/131488886/6829a74f-0a04-4057-aaf8-2935764c1bd1
=> Redirect admin to dashboard after invitation accept

app/helpers/avatar_helper.rb, app/views/components/_avatar.html.erb, app/views/layouts/dashboard.html.erb, app/views/layouts/shared/_navbar.html.erb
Resolves #332 
Created a new view partial, _avatar.html.erb, using nice_partials. This partial handles both scenarios where a user has an attached avatar image and where a default set of initials is used instead.
=> 332 Create Avatar Partial

app/controllers/organizations/organization_profiles_controller.rb, app/models/organization_profile.rb, app/views/devise/registrations/edit.html.erb, app/views/layouts/dashboard/_sidebar.html.erb, app/views/organizations/organization_profiles/_form.html.erb, app/views/partials/_avatarable_form.html.erb, test/integration/organization_profile/organization_profile_edit_test.rb
Closes #164.
Organization admins can now upload a picture for their organization. The picture is displayed in the dashboard navbar, and on the `/organization_profile/edit` page.
This feature relies on previous work done for user avatars, through the `Avatarable` concern and view partial. I tried to reuse as much of the existing code as possible, but if there are any suggestions for improvement please let me know.
A couple other pages could benefit from displaying the organization logo instead of text, namely:
- `app/views/layouts/shared/_navbar.html.erb` line 4
- `app/views/devise/sessions/new.html.erb` line 13
I have not modified these pages yet.
https://github.com/rubyforgood/pet-rescue/assets/85654561/1f9f293a-90c3-4b64-b158-6464e056a651
=> Add images for organization profiles

db/migrate/20231228081555_remove_pause_reason_from_pets.rb
This migration was merged after the removal of the strong_migrations gem. However, it still contained a `safety_assured` block, which led to its failure.
=> Remove safety_assured from migration

app/models/default_pet_task.rb, app/models/task.rb, db/migrate/20240108014846_remove_not_null_constraint_from_default_pet_tasks_description.rb, db/schema.rb, test/models/default_pet_task_test.rb, test/models/task_test.rb
[#417 ](https://github.com/rubyforgood/pet-rescue/issues/417)
-  Added migration to remove null constraint for :description field on default_pet_tasks table
-  Removed presence validation on Task and DefaultPetTask model
-  Removed test checks related to :description presence validation
=>  Create a default pet task and task without a description

app/controllers/organizations/organization_profiles_controller.rb, app/controllers/registrations_controller.rb, app/models/concerns/avatarable.rb, app/views/devise/registrations/edit.html.erb, app/views/partials/_avatarable_form.html.erb, test/integration/organization_profile/organization_profile_edit_test.rb, test/shared/avatarable_shared_tests.rb, test/system/registration_test.rb
🔗 Issue
#426 
- Removed errors appearing on top of user > edit registrations
- Handled error display on both user > edit registrations as well as Organizational Profiles edit where earlier proper error message was not displayed for Attach Picture
- Removed append_avatar method from avatarable and changed all occurrences of :append_avatar to :avatar
- Handled test cases as well
=> Handle Error display on user edit registrations and related to avatarable

app/views/organizations/pets/tabs/_applications.html.erb, test/controllers/organizations/adoption_application_reviews_controller_test.rb
#429 
- Added corresponding profile links to both pet and adopter names
- Asserted the presence of link in controller test
=> Added Links to Corresponding Profiles

app/controllers/matches_controller.rb, app/views/organizations/pets/tabs/_applications.html.erb
Resolves #431 
- Update "New Adoption" Button (Enabled only when status is "Successful Applicant")
- Add tooltip on hover of disabled button (text to can be changed based on stakeholder feedback)
- Fix redirect in matches controller to redirect back to the page the user navigated from (Either pets page or application reviews page) 
[Screencast from 01-12-2024 09:58:31 AM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/dea4947d-3b55-46dc-ae98-979118c62100)
=> 431 update new adoption button

app/views/organizations/pets/tabs/_applications.html.erb
#441 
Removed profile column from adoption application reviews
=> Removing profile column from adoption application reviews

app/controllers/organizations/adoption_application_reviews_controller.rb, app/helpers/adoption_application_reviews_helper.rb, app/views/layouts/shared/_flash_messages.html.erb, app/views/organizations/adoption_application_reviews/update.turbo_stream.erb, app/views/organizations/pets/tabs/_applications.html.erb, app/views/organizations/pets/tabs/partials/_application_status.html.erb, test/controllers/organizations/adoption_application_reviews_controller_test.rb
Resolves #430 
-Add turbo_stream response to adoption_application_reviews_controller 
-Add notes update with modal
-Add change status with dropdown
-Update tests
[Screencast from 01-24-2024 06:30:36 PM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/2a358a3c-67da-4038-8910-f98fa2a77552)
=> 430 Update application reviews/notes with turbo_stream

app/controllers/organizations/default_pet_tasks_controller.rb, app/models/default_pet_task.rb, app/services/organizations/default_pet_task_service.rb, app/views/organizations/default_pet_tasks/_form.html.erb, app/views/organizations/default_pet_tasks/index.html.erb, db/migrate/20240201133430_add_due_in_days_to_default_tasks.rb, db/schema.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb, test/controllers/organizations/default_pet_tasks_controller_test.rb, test/models/default_pet_task_test.rb, test/services/organizations/default_pet_task_service_test.rb
#456 
Adds a `due_in_days` column to default tasks.  When a task is created from the default task, its due date is set to `due_in_days` days from now.
=> Default tasks - due in days

test/controllers/organizations/tasks_controller_test.rb, test/factories.rb, test/integration/organization_profile/organization_profile_edit_test.rb, test/models/organization_profile_test.rb, test/test_helper.rb
Not for a specific issue but this was causing me problems while working on #450, and I think it's an important enough bug that it should be addressed before I finish that feature.
The problem is that currently `ActsAsTenant.current_tenant` can leak between tests. It could also cause problems with `organization` relation assignment not behaving as expected in tests.
tl;dr: With our current test_helper.rb setup, tenant values will leak between tests depending on how they are used and especially if using methods such as `ActsAsTenant.without_tenant` or `ActsAsTenant.with_tenant` in a test. These changes will prevent this from happening and better match the recommendations from ActsAsTenant.
You can read a full explanation below if you want to find out more about how ActsAsTenant works. I …
=> Fix test tenant leakage

app/models/task.rb, app/views/organizations/pets/tasks/_tasks.html.erb
This pr addressed #454  . I have updated the relevant code and add color shading to background of each task depending on its status.
=> Add colour shading to background of each task depending on its 'status' 

app/models/task.rb
Resolves #462 
Fixes error on new Pet creation due to 'default tasks' with optional descriptions and 'tasks' with mandatory descriptions.
-Remove presence: true validation from task's model
=> Change task model to allow optional description

app/javascript/controllers/toggle_completed_controller.js, app/views/organizations/pets/tasks/_tasks.html.erb
This pr addressed #455  . I have updated the relevant code and added a checkbox to show/hide completed tasks.
=> Add checkbox to show/hide completed tasks.

app/models/task.rb, app/views/organizations/pets/tasks/_tasks.html.erb, test/models/task_test.rb
Resolves #471 
This adds a method to the Task model to sort the order in which tasks are returned to the view. I've added scopes for the different criteria then concat the tasks into a single list in the method. I'm not sure if there is a way to do this all in a single query (or if that would provide much benefit) because some parts of the list are ascending and some descending. I am open to suggestions.
[Screencast from 02-21-2024 07:46:34 AM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/d10809e0-2a6b-4bf4-b7c7-1a619505e3c6)
=> 471 Sort Pet Tasks

app/models/organization.rb, app/models/page_text.rb, app/services/organizations/create_service.rb, db/migrate/20240225160909_create_page_texts.rb, db/schema.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb, test/factories.rb, test/models/organization_test.rb, test/models/page_text_test.rb, test/services/organizations/create_service_test.rb
#473 
Adds a `PageText` model with `organization_id`, `about`, and `hero` columns, with index. `about` and `hero` allow nil but not empty strings or strings containing only whitespace. 
Updates create service object to create a page_text for organization, and seed files. 
Adds factory, tests for new model.
=> 473 create page text

.gitignore, app/views/devise/registrations/edit.html.erb, app/views/organizations/home/index.html.erb
[issue #484 ui repair](https://github.com/rubyforgood/pet-rescue/issues/484)
Two sections of the org/root had incorrect background color per the figma file.
Added the bg-white css selector to the two appropriate sections
=> added the bg-white css selector to the sections of org/root per figma

db/seeds/01_alta.rb, db/seeds/02_baja.rb
…y State gem so the value populates as expected in the form for Org profile edit. Also use a real phone number so it passes the phonelib gem validation on form save. The existing number was failing second validation.
Fixes the issue where the country and state are not pre-populated in the form selects on the Org Profile edit page. The reason was because we use the City State gem to load the select and the seed data needs to match the options provided by the gem. 
Also use an actual valid phone number in seeds to prevent the validation error when saving the form in the UI.
=> Update Seeds for Org Profile Coutnry, State, Phone to fix issues

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/issue-auto-unassign.yml, config/application.example.yml
Adding a couple scans as good practice
**Added dependabot**
[Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates) will scan our dependencies and check for updates - this will ensure we will get the most recent versions of our dependencies and any associated security fixes.
**Added CodeQL**
[CodeQL](https://codeql.github.com/) will check our ruby and js files for any vulnerabilities or code smells. This will help us maintain good code quality.
**Removed placeholders**
Removed unused placeholders - these are fake keys to show how to format the file, but we don't need this anyways since it's just standard yaml
=> Repo hygiene

app/controllers/organizations/tasks_controller.rb, app/models/adopter_foster_profile.rb, test/controllers/organizations/tasks_controller_test.rb, test/system/tasks_test.rb
#509 
Fixes task#update action to not remove `next_due_in_days` value if the task is being marked complete. 
I added both a controller test and a system test, not sure if we really need both? Let me know and I can remove one if it's overkill.
=> 509 bug recurring pet task

app/views/layouts/shared/_navbar.html.erb
Adding a demo banner to public testing site. This will make it clear to anyone accessing the site that it is just a demo and will prevent us from confusing prod/staging
=> Add a demo banner for public sites 🤏 

app/controllers/adoptable_pets_controller.rb, app/views/adoptable_pets/show.html.erb, app/views/organizations/pets/tabs/partials/_application_status.html.erb, config/locales/en.yml, test/integration/adoptable_pet_show_test.rb, test/integration/adoptable_pets_index_test.rb, test/test_helper.rb
Fixes #522 
Fixes linked issue and adds integration tests. 
Expectation is that the adoptable_pets views are consistent across users - except for applicants being able to see their own application status 
I don't know how to DRY up these tests - should this be a spec?
=> Fix adoptable_pet issue and add tests

app/controllers/matches_controller.rb, app/models/adopter_application.rb, app/models/match.rb, app/views/organizations/pets/tabs/partials/_application_status.html.erb, config/routes.rb, test/integration/adopter_application_test.rb, test/models/adopter_application_test.rb, test/models/match_test.rb
No issue.
Similar to  #475, I thought `Match` could benefit from refactoring. Note that I will be cleaning it up further, getting rid of `same_organization?` and `get_pet_id` in the Authz PR too.
This started with me changing the routes to the Rails convention. I personally found it a little confusing that sometimes we refer to adoptions as "adoptions" and sometimes as a "match". This PR tries to at least make it so that things using `Match` refer to it as a "match". This includes things like the strong params name.
The other portion of this PR works to get `AdopterApplication` logic out of `MatchesController`. I think this business logic belongs in the models. I also like setting withdraw for an individual object more as an instance method rather than as a class method like …
=> Refactor matches

app/controllers/registrations_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
Fixes https://github.com/rubyforgood/pet-rescue/issues/526
Only adopter users will be using the registrations/new form as staff and fosterers will be handled with invites. 
We build in instance of the associated adopter_account in the registrations controller #new override action but we were missing the nested attributes for adopter_account in the form. Now when a user signs up with this form, an associated adopter account is created.
I did toy with some callback on the User model to create the associated adopter account, but I didn't really consider it User domain logic per se, and keeping the logic on the registrations controller and view seems to be appropriate enough.
=> Fix: create associated adopter account when user signs up with registrations/new form

app/controllers/organizations/dashboard_controller.rb, app/controllers/organizations/invitations_controller.rb
Related to #466 
Fix a few organization contexts that should have been pointing to `Current.organization`.
This change avoids possible error raises from user not existing, and they should instead get unauthorized, redirected, and shown an authorization message.
=> Fix organization contexts for policies

app/views/organizations/pets/tabs/_overview.html.erb
Resolves #557 
Conditionally show/hide pet summary column's based on if the pet is adopted or not.
Unadopted
Adopted
=> 557 UI: Remove inapplicable content for adopted pet in Pet's summary

app/assets/stylesheets/custom.scss, app/javascript/controllers/dropdown_controller.js, app/views/layouts/shared/_navbar.html.erb
#548 
Note: Enthusiastic to hear cleaner, alternative approaches. I am not a fan of bootstrap and avoid it in my personal projects, so I may not be familiar with some better ways to overwrite some of this behavior.
This PR aims to make the navigation bar more accessibility friendly. Currently the right corner navbar on desktop view only shows if you hover the icon. This is terrible for keyboard users as it makes it potentially impossible for them to open it, and that's the only place where some of those links live!
This behavior is coming from media queries from the theme we are using. Some of the culprit rules are here:
```css
@media (min-width: 1200px) {
.navbar .dropdown-menu {
display: block;
opacity: 0;
transform: translateY(20px);
transition: all 0.3s ease-in-out;
visibility: …
```
=> 548 navbar accessibility

app/views/layouts/shared/_navbar.html.erb
https://github.com/rubyforgood/pet-rescue/issues/544
After log in, Log In button still appeared on dropdown menu, in mobile view.
=> 554 - link_to Log In removed from navbar view

Gemfile, Gemfile.lock
[chartkick](https://github.com/ankane/chartkick) was being used to generate charts in the previous version of this app. We aren't currently using this but will revisit later
=> Removing chartkick

app/views/layouts/dashboard/_sidebar.html.erb
[572](https://github.com/rubyforgood/pet-rescue/issues/572)
Currently the navigation bar icon on the Dashboard page is not clickable. This change makes this icon clickable and then redirects the user to the organizations root page.
=> 572 Dashboard navbar icon redirects to organization's root page

app/models/adopter_application.rb, app/models/match.rb, db/migrate/20240321032816_change_index_in_matches_on_pet_id_to_unique.rb, db/migrate/20240322214921_index_adopter_applications_on_account_and_pet.rb, db/schema.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb
#555 
> an adopter to can have more than one adoption applications but can only have 1 application per pet
Added validations to model and to schema so that the Rails app checks for uniqueness of this relationship.
> a pet can only have 1 match (multiple adopters cannot "adopt" the same pet)
Added uniqueness validation to model and schema for pets on matches.
I also updated the seed file, so that it will redo invalid adopter application sampling attempts.
I did not make any UI changes, as currently adopter applications disappear from the index view when an adoption is made.
=> 555 adopter app validations

app/views/adopter_applications/index.html.erb
https://github.com/rubyforgood/pet-rescue/issues/543
Fixed : In the "My Applications" view for an adopter - The pet image is not bound and can take up the whole screen.
=> fix: made pet image bound

app/controllers/organizations/base_controller.rb, app/controllers/organizations/page_texts_controller.rb, app/models/concerns/authorizable.rb, app/policies/organizations/page_text_policy.rb, app/views/layouts/dashboard/_sidebar.html.erb, app/views/organizations/home/index.html.erb, app/views/organizations/page_texts/_form.html.erb, app/views/organizations/page_texts/edit.html.erb, config/breadcrumbs.rb, config/routes.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb, test/controllers/organizations/page_texts_controller_test.rb, test/policies/organizations/page_text_policy_test.rb, test/system/home_page_test.rb, test/system/users_test.rb
Resolves #479 #480 
This PR adds ability for staff admin to update org page text.  
- Implemented edit and update actions to allow staff admins to modify the hero and about attributes. 
- Created corresponding views to allow staff to edit page text from dashboard along with tests for coverage. 
- Updated about section in the home page view to use attributes from PageText or existing default message.
=> 479 480 page text controller and edit form

app/views/layouts/shared/_navbar.html.erb
[Adjust registration and session links in navbar](https://github.com/rubyforgood/pet-rescue/issues/601)
Added Conditions to display actions when expected. Display logout when user signed in & and link signup in Nav bar.
Fix for Exhibit 1 & 3
Fix for Exhibit 2
=> Adjust registration and session links in navbar (#601)

app/controllers/organizations/invitations_controller.rb, app/controllers/registrations_controller.rb, test/controllers/organizations/invitations_controller_test.rb, test/controllers/registrations_controller_test.rb
#600 
This implements assigning the role of `:adopter` to `Users` when they register as an adopter. Currently, users who sign up for an account do not get this assignment, and thus do not have adopter permissions to navigate the site.
It also adds tests for this behavior, as well as for the existing assignment of the `:staff` and `:admin` roles from the invitations.
This does not implement the assignment of the `:fosterer` role as that role has not been added yet, and we also have not created the workflow for staff inviting fosterers yet.
I think we should leave the issue open for now to remember that we need to do this for fosterers. I've marked the tasks related to this PR as completed in the issue.
Some small naming/typo fixes are also included.
=> 600 assign roles

app/controllers/registrations_controller.rb, app/views/layouts/shared/_navbar.html.erb
https://github.com/rubyforgood/pet-rescue/issues/622
Refactors top nav to replace links with relevant links and remove avatar and place the avatar dropdown links in navbar. 
Also fixes the error we were getting if a signed in user tries to access sign up page.
https://www.loom.com/share/8b171d6bc07f417e890e615f39c68cca?sid=db9f76dc-bb09-4448-9d76-6721aa1f0e87
=> 622 refactor top navbar

app/models/concerns/authorizable.rb, test/factories/adopter_foster_accounts.rb, test/factories/staff_accounts.rb, test/factories/users.rb, test/integration/adoptable_pet_show_test.rb, test/integration/adoption_application_reviews_test.rb, test/policies/adopter_application_policy_test.rb, test/policies/attachment_policy_test.rb, test/policies/organizations/adoptable_pet_policy_test.rb, test/policies/organizations/adopter_application_policy_test.rb, test/policies/organizations/adopter_foster_profile_policy_test.rb, test/policies/organizations/dashboard_policy_test.rb, test/policies/organizations/default_pet_task_policy_test.rb, test/policies/organizations/invitation_policy_test.rb, test/policies/organizations/match_policy_test.rb, test/policies/organizations/organization_profile_policy_test.rb, test/policies/organizations/page_text_policy_test.rb, test/policies/organizations/pet_policy_test.rb, test/policies/organizations/profile_review_policy_test.rb, test/policies/organizations/staff_account_policy_test.rb, test/policies/organizations/task_policy_test.rb
#599
This implements the `:fosterer` role for authz purposes. It does so by implementing `FOSTERER_PERMISSIONS`. It also adds the fosterer factory and a fosterer context to many of the policy unit tests.
Adding the fosterer factory led me to refactor the user factory slightly in regards to how roles were assigned in our factories. It would be worth making sure that those changes make sense.
Roles were previously being added through the account factories. This refactoring moves the role assignment to the user factory.
The roles are associated now with `User` records, not `Account` records. Coupling the accounts with the roles was making testing for role related behavior clunky, especially since adopter and fosterers share the same account type, `AdopterFosterAccount`. 
For consistency, I …
=> 599 add fosterer role

CONTRIBUTING.md, README.md
Postgres is needed to run locally, but the instructions didn't mention this. This minor change provides instructions that help get started running locally on MacOS.
=> Add instructions for Postgres

app/controllers/organizations/matches_controller.rb, app/models/match.rb, app/views/organizations/pets/tabs/partials/_application_status.html.erb, db/migrate/20240418120309_add_match_type_to_matches.rb, db/schema.rb, db/seeds/01_alta.rb, db/seeds/02_baja.rb, test/controllers/organizations/matches_controller_test.rb, test/factories/pets.rb, test/mailers/match_mailer_test.rb, test/models/match_test.rb, test/policies/organizations/match_policy_test.rb
Resolves #643 
This adds the following columns to the Matches table:
`match_type` with null false and enum for `adoption` and `foster`
`start_date :datetime`
`end_date :datetime`
The model was updated for the enum and the controller updated for the new params. The finalize adoption button adds the match_type param. Seeds updated for adoptions.
Test were updated. The only new test added is the validation of the enum. If there is any other new test coverage you can think of please let me know.
=> Change matches table to handle adoptions and fosters

app/models/faq.rb, app/models/organization.rb, db/migrate/20240419164004_create_faqs.rb, db/schema.rb, test/factories/faqs.rb, test/models/faq_test.rb, test/models/organization_test.rb
Resolves #474 
Add faq table and model to allow an org to CRUD faq questions and answers. FAQ's are able to be added via the console.
FAQ table:
`question :string` null false
`answer :text` null false
`order :integer`
index faqs on organization_id / foreign key
=> 474 Add FAQ table and model

app/controllers/concerns/organization_scopable.rb
#664 
This updates `after_sign_in_path_for` so that adopters and fosterers are redirected to their dashboard now upon login. It also updates the current if statement so that the staff dashboard redirect is using the `DashboardPolicy` instead of `PetPolicy` (which was old logic).
=> 664 Redirect to dashboard

db/seeds/02_baja.rb
Resolves #682 
Currently the PageText data will not displaying for Baja org but will display for Alta.
The seed file for Baja has a second creation of PageText which is believed to be causing an issue with the `home/index` view. This PR removes the second PageText.create
=> Fix Baja Seed File

app/models/adopter_foster_profile.rb, app/models/concerns/phoneable.rb, app/models/organization_profile.rb, app/views/layouts/shared/_footer.html.erb, app/views/organizations/adopter_fosterer/profiles/show.html.erb, app/views/organizations/staff/profile_reviews/show.html.erb, test/models/concerns/phoneable_test.rb, test/system/home_page_test.rb
Adds the organization contact information to the footer partial
https://github.com/rubyforgood/pet-rescue/issues/171
- Replaces the dummy contact info in the footer with the org's contact info
=> feat: replace dummy contact info with org info

README.md
#693
Adds documentation to help new developers onboard with Action Policy.
Note that this PR adds a brief note to the README that links to our wiki. I have the wiki content below if you have suggested revisions.
---
If you find yourself writing a conditional checking the question, "Is the user **allowed** to view/do this?" that is an authorization concern. Pet Rescue utilizes the gem [Action Policy](https://github.com/palkan/action_policy) as our authorization framework. If you are familiar with Pundit, you will see many similarities. If you want to learn more about authorization or have questions about how Action Policy works, [their documentation](https://actionpolicy.evilmartians.io/#/) is excellent.
If a policy object is not behaving as you expect, check out the defaults set in …
=> Add Authorization section to README with link to wiki

app/views/organizations/home/index.html.erb
https://github.com/rubyforgood/pet-rescue/issues/702
Removed the Page highlights section from the Organization root page
Before
After
=> fix: Removed Page highlights section

app/controllers/organizations/staff/page_texts_controller.rb
https://github.com/rubyforgood/pet-rescue/issues/700
Changed the edit_page_text_path to edit_staff_page_text_path in Organizations::Staff::PageTextsController in the update action as suggested in original issue
=> fix(700): fix path helper method name

app/views/organizations/staff/staff/_deactivate_toggle.html.erb, app/views/organizations/staff/staff/update.turbo_stream.erb
Resolves #723 
This fixes the staff deactivate toggle by using replace_all and targeting a class instead of an id.
The page loads both cards and tables at the same time so one staff member would have two toggles with the same id on the page causing issues. By changing the id to a class and targeting all classes matching the target name this resolves the issue.
[Screencast from 05-17-2024 07:07:23 AM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/3ccc6588-f76c-446a-a1fa-84b25c076846)
=> Fix Staff deactivate toggle

app/controllers/organizations/adoptable_pets_controller.rb, app/controllers/organizations/staff/page_texts_controller.rb, app/models/page_text.rb, app/views/organizations/adoptable_pets/show.html.erb, app/views/organizations/staff/page_texts/_form.html.erb, config/locales/en.yml, db/migrate/20240518203140_add_adoptable_pet_info_to_page_texts.rb, db/schema.rb, test/integration/adoptable_pet_show_test.rb
#718 
Adds the new column for adoptable pet info to page texts table and updates the relevant form and the adoptable pets show view to display info if present. 
The form looked a little weird with the label and header being the same text so I tried to come up with something that would convey the same meaning but not be identical. Happy to change it if you want. 
The form with a placeholder: 
Adoptable pets view with information:
=> 718 allow staff customize text adoptable pet show

app/views/organizations/home/index.html.erb
#701 
This is a temporary fix to ensure a consistent layout on the org home page. Org staff can upload two images without any constraints on their dimensions.
This PR uses a ratio of 1:1. The ratio can be changed via bootstrap if there is a aspect ratio that better fits the layout and would least affect the most common upload dimensions. 
Compromise:
- Landscape photos will be cropped on the left and right
- Portrait photos will be cropped top and bottom
=> Temp fix for About Us images with varying size/aspect ratios

README.md, config/database.yml, docker-compose.yml
This provides an _alternative_ to having to install a local postgres
service, and presents a mechanism for running ports isolated from any other
docker service clusters that may be running on the same machine.
=> Add a docker-compose file to launch local service dependencies

app/views/organizations/staff/pets/tabs/_overview.html.erb, test/system/pet_overview_test.rb
Fixes: #754
We wanted to make a change to the [pet overview tab](http://127.0.0.1:3000/alta/staff/pets/32) when viewing a specific pet. Previous to the change, half of the columns in the overview table were being hidden if the pet had any matches at all. This change makes it so that if there are no matches OR the match type is `:foster`, the full overview table is still viewable by the staff. The only time part of the overview should be hidden is if a match is made that is the regular `:match` type, AKA an adopter. I added a check in the `_overview.html.erb` partial for the `:foster` type match, and added a new test file, `pet_overview_test.rb` to make sure this functionality was working. I also QA tested manually via the console, and it seems to be working.
A match has been made for …
=> Show Pet Overview for :foster type matches

app/controllers/organizations/adopter_fosterer/adopter_applications_controller.rb, app/views/organizations/adopter_fosterer/adopter_applications/_application_cards.html.erb, app/views/organizations/adopter_fosterer/adopter_applications/_applications_table.html.erb, config/locales/views/dashboard.en.yml, test/system/adoption_fosterer_test.rb, test/system/login_test.rb
https://github.com/rubyforgood/pet-rescue/issues/757
Added a feature to the "adopter applications" page (the version that is part of the fosterer dashboard)
Now after an application is withdrawn via the "Withdraw Application" button, it is displayed with a "Delete" button which flags the application to no longer show in their list.
I'm going to try to come back and do this later, I delayed making a PR after I finished this because I was going to take a screen recording, but I realized with a bunch of people working on the same codebase I should actually get my code in for everyone to see
=> Ability to remove a withdrawn application from list

app/views/organizations/adoptable_pets/show.html.erb
#774 
Remove plain adoption pending text from below pet name on the pet show page. Replace it with a badge
=> Add adoption pending badge

app/views/organizations/staff/staff/_deactivate_toggle.html.erb
Resolves #804 
Deactivate toggle is disabled for the current user's account
[Screencast from 06-03-2024 08:53:08 PM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/62818658-1a42-4599-ba4e-44207f279390)
=> Disable deactivate toggle if account is current user

app/controllers/organizations/staff/dashboard_controller.rb, app/models/task.rb, app/policies/organizations/dashboard_policy.rb, app/views/organizations/staff/dashboard/incomplete_tasks.html.erb, app/views/organizations/staff/dashboard/index.html.erb, app/views/organizations/staff/dashboard/tasks.html.erb, config/routes.rb, test/controllers/organizations/staff/dashboard_controller_test.rb, test/models/task_test.rb, test/system/dashboard_test.rb
#707 
- Added new scopes in task model to get not_overdue and overdue tasks
- Updated Dashboard controller index method to calculate number of incomplete and overdue tasks in organization
- Added two new methods in dashboard controller to fetch for each pet number of incomplete and overdue tasks
- In dashboard index view, added metric to display pending and over tasks counts
- On click of each metric, we render pet table details using turbo frame
Dashboard Page
Dashboard Page with Incomplete Tasks
Dashboard Page with Overdue Tasks
=> 707 Dashboard metric for Incomplete and Overdue tasks

app/models/concerns/avatarable.rb, app/models/person.rb, db/migrate/20240609170030_create_people.rb, db/schema.rb, test/factories/people.rb, test/models/person_test.rb
A person represents a flesh-and-blood human in the system, and should be
the core data model representing _most_ actors in the system.
Eventually, we will want to attach the filled form results to a person
record, and Accounts should belong to a person to grant the ability to
log into the system.
Note that this table explicitly does _not_ include any authentication
related material.  tokens generated for things like magic login, or
authorization credentials for regular users, should exist in their own
dedicated classes.  I'll follow up with an email+token based auth flow
implementation later.
=> Generate a person model

config/environments/test.rb
#830
Simple fix for a deprecated Action Dispatch setting value. This was being reported in the test results.
=> Update deprecated Action Dispatch variable value

app/models/custom_form/submitted_answer.rb, db/migrate/20240619203450_rename_answers_to_submitted_answers.rb, db/schema.rb, test/factories/custom_form/submitted_answers.rb, test/models/custom_form/submitted_answer_test.rb
#833 
Rename answer to CustomForm::SubmittedAnswer throughout the application.
- Added new migration to rename answer to submitted_answers
- Nested answers model under CustomForm and renamed it to submitted_answer
- Annotated model with updated details
- Updated test file to match with nested module and updated name.
NA
=> Changes for renaming answer to CustomForm::SubmittedAnswer

app/views/organizations/staff/pets/_pet_table.html.erb
[859](https://github.com/rubyforgood/pet-rescue/issues/859)
This change removes the `Copy link` option in the ellipsis menu in the Pets table. 
Before:
After:
=> Issue 859 - Remove Copy link option from the ellipsis menu in the Pets table

app/models/organization.rb, app/models/person.rb, app/models/user.rb, db/migrate/20240719034910_add_person_id_to_user.rb, db/schema.rb, test/models/organization_test.rb, test/models/person_test.rb, test/models/user_test.rb
#875 
This adds a `person_id` column to the users table in the database, and wires up the various associations.
There's also a little bit of "rails magic" in the form of a `before` hook on user creation, which ensures that a person will be connected to any newly created users:  first, it will attempt to match an existing user with the same email address, and failing that, a new person will be created with a basic set of attributes.
=> User person

app/controllers/organizations/adopter_fosterer/donations_controller.rb, app/views/layouts/adopter_foster_dashboard.html.erb, app/views/organizations/adopter_fosterer/donations/index.html.erb, app/views/static_pages/_donate_content.html.erb, app/views/static_pages/donate.html.erb, config/locales/en.yml, config/routes.rb
…oster dashboard
https://github.com/rubyforgood/pet-rescue/issues/887
PR refactors the donate page to use generic copy and render the org's donate link in the card. The view logic was moved to a partial that could be used in the adopter foster dashboard context as well, as I think it's nice to keep link clicks in the dashboard within the dashboard. Gets rid of no longer required donation routes and logic that was specifically for baja pet rescue's paypal page.
If there is a donation URL, that is displayed, otherwise the link to contact us is displayed.
These pages could do with some design love, but they are MVP ready for now. 
with URL
=> Refactor donate page

docker-compose.yml
This runs bundle install when starting up the containers. It means a slightly slower start up, but I am otherwise having to enter the bundle install command manually in the docker-compose file which is more of a pain. I also configured SASS service to remain open and interactive, otherwise it boots up, then exits.
=> Configure docker-compose

app/controllers/dev_contacts_controller.rb, app/mailers/dev_contacts_mailer.rb, app/views/dev_contacts/new.html.erb, app/views/dev_contacts_mailer/send_message.html.erb, app/views/dev_contacts_mailer/send_message.text.erb, app/views/layouts/shared/_footer.html.erb, config/locales/en.yml, config/routes.rb, test/controllers/dev_contacts_controller_test.rb, test/mailers/dev_contacts_mailer_test.rb, test/mailers/previews/dev_contacts_mailer_preview.rb
#914 
Adds ability to contact the dev team. 
I used the existing Contact model since they have the same attributes. The mailer has a placeholder for the email. 
The form (same styling as other contacts form):
The footer, wide:
medium:
small:
=> 914 feedback for dev team

app/controllers/organizations/adoptable_pets_controller.rb, app/controllers/organizations/staff/adoption_application_reviews_controller.rb, app/controllers/organizations/staff/default_pet_tasks_controller.rb, app/controllers/organizations/staff/manage_fosters_controller.rb, app/controllers/organizations/staff/pets_controller.rb
#944 
Replaced `items` with `limit` to improve record handling and ensure accurate implementation of record limits.
=> Replaced items with limit in the pagy method

app/views/layouts/dashboard/_sidebar.html.erb
#954 
-[x] Change nav-header color to white
-[x] Disable the Forms link in navigation
=> 954 - Update nav-header color and disable Forms link

app/views/organizations/staff/adopters/_adopter_cards.html.erb, app/views/organizations/staff/adopters/_adopter_table.html.erb, app/views/organizations/staff/adopters/index.html.erb, app/views/organizations/staff/fosterers/_fosterer_cards.html.erb, app/views/organizations/staff/fosterers/_fosterer_table.html.erb, app/views/organizations/staff/fosterers/index.html.erb, app/views/organizations/staff/staff/_staff_cards.html.erb, app/views/organizations/staff/staff/_staff_table.html.erb, app/views/organizations/staff/staff/index.html.erb
https://github.com/rubyforgood/pet-rescue/issues/971
The purpose of this PR is to remove the toggle button functionality and use the responsive way of displaying listings in the rest of the system for: fosterers, staff, and adopters.
https://jam.dev/c/5c8a47a1-3a55-4744-b8a7-fb9b9f912c5c
=> remove toggle to cards for people features

app/views/static_pages/_donate_content.html.erb
N/A
Updates styling on donate partial to fit both the `/donate` and `adopter_fosterer/donations` views
=> Donate partial style update

app/models/pet.rb, app/views/organizations/staff/pets/index.html.erb, test/controllers/organizations/staff/pets_controller_test.rb, test/models/pet_test.rb
https://github.com/rubyforgood/pet-rescue/issues/969
This PR addresses a bug in the search filter resulting in the `unadopted` filter to not work as expected.
Changes made:
* Defines a missing `unadopted` scope.
* Update the `ransack_adopted` method to use strings instead of booleans to get around a known bug. Kudos to @coalest for pointing me to https://github.com/activerecord-hackery/ransack/issues/1375#issuecomment-1674885632.
* Add test coverage for `ransack_adopted` to ensure the adopted/unadopted filters work.
* Add missing test coverage for other filters in the search.
=> Fix Pet filter bug in staff view

app/views/organizations/staff/adoption_application_reviews/update.turbo_stream.erb, app/views/organizations/staff/pets/tabs/_applications.html.erb, app/views/organizations/staff/pets/tabs/partials/_application_info_card.html.erb, app/views/organizations/staff/pets/tabs/partials/_application_info_table_row.html.erb, test/integration/adoption_application_reviews_test.rb
https://github.com/rubyforgood/pet-rescue/issues/1035
Cannot use a div as a child inside a table. So, the div with the ID to replace sits outside the table and the turbostream updates it...and does not replace the old row...see gif.
bug
Fix
=> Fix adopter application review status change bug

app/models/pet.rb, db/migrate/20241008095758_add_application_paused_not_null_constraint_to_pets.rb, db/schema.rb
There is no direct issue for this PR, but it is related to #795. 
In the issue mentioned above, we want to add a filter to pets for their paused status, which is a boolean value with a default set to false. A minor issue is that there is no `NOT NULL` constraint on that column so technically a pet could have `NULL` for their paused status and therefore would be missing when filtering by true or false.
This PR assumes that a `NULL` value for `application_paused` doesn't make sense for a pet.
=> Add NOT NULL constraint to application_paused field on pets

app/models/concerns/pet_ransackable.rb, app/models/pet.rb, app/views/organizations/staff/pets/index.html.erb, test/controllers/organizations/staff/pets_controller_test.rb
#795 
- Added filters for application_paused, published, and placement_type in the staff pets view.
- Changed text in filter from "Unadopted" to "Not adopted"
- Added controller tests
- Moved ransack logic on Pet model to concern
Short demo of new filters: 
[screencast2.webm](https://github.com/user-attachments/assets/79d8ccaf-f490-417c-bb5a-7a9ba1e0896e)
On mobile, the filters are taking up a lot of screen real estate, so if mobile is important could be improved in the future.
1. For the `placement_type` filter, I wasn't sure if this should just be a simple filter like I have implemented here, or if it should be something more. Because right now it seems confusing that you can have a pet that has already been adopted, but it will show up under "Adoptable" for Placement Type. Is this the …
=> 795 Add additional filters on staff pet view

app/controllers/organizations/adoptable_pets_controller.rb, app/controllers/organizations/adopter_fosterer/likes_controller.rb, app/controllers/organizations/staff/pets_controller.rb, app/models/concerns/pet_ransackable.rb, app/models/pet.rb, test/controllers/organizations/adoptable_pets_controller_test.rb, test/factories/matches.rb, test/models/pet_test.rb
#1021 
- Refactored `Pet#is_adopted?` method to reference `Match` association rather than `AdopterApplication`
- Fixed related tests
=> 1021 Refactor Pet instance method to use the Match model instead of the AdopterApplication model

app/views/organizations/adoptable_pets/index.html.erb, app/views/organizations/adoptable_pets/show.html.erb
#1061 
Added a species identifier next to the pet name on the /adoptable_pets page.
Not logged in:
Logged in as adopter fosterer:
Logged in as staff:
Mobile:
=> Add species identifier next to pet name on adoptable pets view

app/views/organizations/home/index.html.erb, test/system/home_page_test.rb
closes issue #1071 
#1071 issue fixed. Changed the organization home page link from "create account" to a button styling as "Sign Up".
Also added a small test in test/system/home_page_test.rb to check if the button is there with the correct text.
=> Change org/home create account button to sing up and style change

app/views/organizations/adoptable_pets/index.html.erb, app/views/organizations/adopter_fosterer/likes/index.html.erb, test/controllers/organizations/adoptable_pets_controller_test.rb
#1068 
Kilograms was hard coded in a few of our views, so I switched them to use the pet's `weight_units` instead.
=> Fix weight units bug in views

config/locales/en.yml
https://github.com/rubyforgood/homeward-tails/issues/1099
We want to update copy to remind users to use their Homeward Tails email when filling out these embedded forms.
=> 1099 - Update Embedded Form Copy

app/policies/application_policy.rb, app/policies/organizations/organization_policy.rb
#1098 
Log in as staff and go to the dashboard. In the navbar there should be a Settings link under Admin section. This is not visible, but you can access it by going to /staff/organization/edit.
In `OrganizationPolicy`, the `verify_active_staff!` pre-check was failing because the organization method was returning nil. This happened because the organization method in `ApplicationPolicy` was set to always call `record.organization`, which only works when `record` is something associated with an organization (like a CustomPage, User, or another related class). However, if `record` itself is an `Organization`, `record.organization` is not valid. To fix this, I updated the organization method to return record directly when record is an Organization, ensuring the method works correctly for …
=> 1098 - Fix  settings link under Admin section

app/views/layouts/shared/_footer.html.erb
Updated footer links to point to the correct routes for legal pages, based on the working signup links. Also addressed inconsistency in link text, changing 'Terms of Use' to 'Terms and Conditions' to match the signup page.
=> Update routes for footer links to legal pages

app/views/organizations/adoptable_pets/index.html.erb
This PR implements adding an empty state message to the adoptable pet view when a user searches for a pet and does not yield any results. This will help with user confusion by giving a descriptive message: " We don't have any pets matching your search criteria. "
=>  add: empty state message to adoptable pets view

db/migrate/20241122053814_add_locatable_to_locations.rb, db/migrate/20241127052013_backfill_locatable_for_locations.rb, db/migrate/20241127052542_remove_organization_from_locations.rb, db/schema.rb
#1187 
Fixes migration by breaking it up into steps and including back filling.
Note this ignores some of the strong migrations practices, but this is literally affecting one Location record, so it's unnecessary to worry about write times.
=> 1187 Update migrations for backfilling

config/deploy.yml, config/environments/production.rb
Resolves #1189 
This permits the hosts "www.homewardtails.org" and "homewardtails.org" in production. The kamal proxy was also updated to include the www subdomain.
One thing I considered was added a route to redirect all www traffic to the naked domain( [reference](https://masilotti.com/rails-redirect-www/) ). However, I ran into a bunch of failing test and I'm not familiar with this enough to resolve it without guessing. This is probably a lower priority but worth mentioning.
=> #1189 Add www to config.hosts and proxy

config/environments/production.rb
Adding the hosts names to config.hosts causes the deployment to fail.
```
INFO [0fb5bacc] Running docker exec kamal-proxy kamal-proxy deploy homewardtails-web --target="d9ef7a514e43:3000" --host="homewardtails.org" --host="www.homewardtails.org" --tls --deploy-timeout="30s" --drain-timeout="30s" --buffer-requests --buffer-responses --log-request-header="Cache-Control" --log-request-header="Last-Modified" --log-request-header="User-Agent" on homewardtails.org
ERROR Failed to boot web on homewardtails.org
```
The www subdomain does works by defining the host name in deploy.yml.  This was in the previous commit. I did a kamal deploy from my machine without the config.hosts set and www.homewardtails.org worked in production.
Config.hosts is to help prevent DNS rebinding attacks. I'm not sure …
=> Fix deployment failure - Hosts

app/services/organizations/importers/google_csv_import_service.rb
I missed this in the last csv import change. The service skips the column "Email" when creating the question/answer as we don't need that duplicated since the association is based on email. 
The last change added the array of possible "Email" names. This uses the new variable.
=> Fix - Skip email form answer

app/mailers/sign_up_mailer.rb, app/views/adoption_mailer/new_adoption.html.erb, app/views/foster_mailer/new_foster.html.erb, app/views/organization_mailer/create_new_org_and_admin.html.erb, app/views/sign_up_mailer/adopter_welcome_email.html.erb, config/environments/production.rb
I removed the `/` from where we were defining script name in mailers, but I realized I just needed to remove the trailing `/` in the config...this fixes that mistake and shoud fix all links in production e.g., the forgot password redirect to reset password.
=> Mailer fix

app/views/organizations/adopter_fosterer/adopter_applications/_application_cards.html.erb, app/views/organizations/adopter_fosterer/adopter_applications/_applications_table.html.erb
Resolves #1056 
http://localhost:3000/alta/adopter_fosterer/applications
I disabled the link to a pet's profile under the adoption applications if the adoption has been made. I utilized the method is_adopted? to simplify this issue. I did not write any new tests.
=> Disabled link for adopted pets under adoption applications

app/views/organizations/staff/adopters/_adopter_table.html.erb, app/views/organizations/staff/staff/_staff_table.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1223
This change removes the action column in the staff/staff and staff/adopters tables, which are currently not doing anything.
=> Remove action column in staff/staff and staff/adopter tables

app/views/root/index.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1063
-  Removed text-primary class and added btn-primary class for contrast
=> Fixed contrast for Learn more about Ruby For Good button

app/views/layouts/shared/_head.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1242
- Updated the browser tab title and removed unnecessary quote
=> Updated browser tab title to Homeward Tails

config/deploy.yml
This add a few Kamal aliases.
Each of these connects to the currently running container on the production server.
`kamal shell` - opens bash in the containner
`kamal console` - opens the rails console
`kamal logs` - display's the last 10 lines of the productions log and follows as its updated
=> add aliases

app/services/organizations/importers/csv_import_service.rb
The validation error is correctly returned now. I also fixed the row index. Headers are skipped so the count was off by one.
=> CSV Import - correctly report validation error for timestamp

config/locales/en.yml
https://github.com/rubyforgood/homeward-tails/issues/1260
Updates the footer title from Pet Rescue to Homeward Tails
=> fix: switch footer title to Homeward Tails #1260

app/controllers/organizations/home_controller.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/dashboard/_sidebar.html.erb, app/views/layouts/shared/_navbar.html.erb, app/views/organizations/home/index.html.erb, app/views/organizations/staff/organizations/_form.html.erb, test/integration/organization_profile/staff/organization_edit_test.rb
Makes some small fixes in the UI
- devise forms are now consistent 
- navbar now shows org logo if present
- featured pets on org root are now standardized heights
=> Small fixes

app/views/layouts/adopter_foster_dashboard.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1226
Used the `asset_path` helper to set the background image of the banner div.
=> Use asset_path helper for banner background image

app/models/contact.rb, app/models/organization_account_request.rb, app/services/organizations/create_service.rb, app/views/layouts/adopter_foster_dashboard.html.erb, app/views/organizations/adoptable_pets/index.html.erb, app/views/organizations/staff/pets/index.html.erb, app/views/shared/_location_fields.html.erb
Fixes bugs found by @mgrigoriev8109 [here](https://rubyforgood.slack.com/archives/C05JB50LEN5/p1734574101268989)
=> Some more small fixes

app/views/layouts/shared/_navbar.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1236
Reordered nav items to be mobile first and hid the organization name on xs screens.
https://github.com/user-attachments/assets/bcc5ea77-8dfc-4c40-b500-cdd3208d7bed
=> Reorder nav items for mobile and hide org name

app/views/shared/_location_fields.html.erb
[Original Issue](https://github.com/rubyforgood/homeward-tails/issues/1287)
Resizes input columns in shared `_location_fields.html.erb` partial to make the width consistent.
=> Issue #1287: Fixing input widths for org account request

app/views/organizations/adopter_fosterer/external_form/index.html.erb, config/locales/en.yml
It didn't feel right the way we had the browse pets buttons under the iframe form after signing up. So I have updated to go to include a button to go to dashboard instead, and added more detail to the text. 
New sign up
When form has not been submitted or imported
When form has been submitted and imported
=> update the custom form flow

app/views/organizations/staff/fosterer_invitations/_form.html.erb, app/views/organizations/staff/fosterer_invitations/new.html.erb
#1288 
Clean up some stylings while making some design decisions along the way. One thing I decided to try out was to put all input fields in the same column rather than trying to split them. I've been told that it is best practice for design to not do two column forms. The reasoning to me makes sense, you don't want to change a person's context when reading from left to right and downwards. This also solves the problem with handling mobile mode as it already is stacked on top of each other.
I recommend sticking to this pattern since there will less work figuring out what the next styling should be. My rule of thumb is stick to the vertical forms until it breaks and you need to introduce something else more unique.
Desktop:
Mobile:
=> Improve design of the Foster Invite form using vertical form inputs

app/views/layouts/adopter_foster_dashboard.html.erb
N/A
Thought we should increase the container of the adopter dashboard to be fluid. I think we are losing space for content via the container restricting the size of the dashboard. See snapshots below:
=> Increase size of the dashboard for adopters to be fluid to take advantage of viewport space

app/controllers/concerns/attachment_manageable.rb, app/controllers/organizations/staff/external_form_upload_controller.rb, app/views/organizations/staff/external_form_upload/index.html.erb, app/views/organizations/staff/shared/_attachment_form.html.erb
[Original Issue](https://github.com/rubyforgood/homeward-tails/issues/1319)
- Updates text under upload input to inform user that only CSV files will be accepted
- Adds a validation within the `create` action of the controller to display an alert if user uploads a file type other than CSV.
_New copy and error message on top_
=> Issue #1319 - Update file type description and add CSV file type validation

app/controllers/registrations_controller.rb, test/controllers/registrations_controller_test.rb, test/system/registration_test.rb
#1227 
This update utilizes Devise's after_update_path_for method to handle
user redirection after updating their registration.
If the user is part of the adopter or fosterer roster, and associated
with a valid organization they will be redirected to their adopter/fosterer dashboard.
If the user is an admin or super admin, and associated with a valid
organization they will be redirected to their staff dashboard.
If neither condition is met, the user will be redirected to the root path.
Adds: Controller tests for user registration updates:
Test case for adopter/fosterer user redirection.
Test case for staff user redirection.
Adds: update on registration test file to account for new update redirect
=> Update: User Registration Redirect Path

app/views/organizations/staff/dashboard/_pets_with_incomplete_or_overdue_tasks.html.erb, app/views/organizations/staff/dashboard/index.html.erb
[Original issue](https://github.com/rubyforgood/homeward-tails/issues/1326)
- Deletes unused Rescue card
- Moves Tasks card to the bottom to be closer to the Overdue Pet Tasks card
- Removes unneeded sex column from table
=> Issue #1326: Refact mobile view of staff dashboard

app/controllers/concerns/attachment_manageable.rb, app/controllers/organizations/staff/external_form_upload_controller.rb, config/locales/en.yml, test/controllers/organizations/staff/external_form_upload_controller_test.rb
Fixes a bug caused by `params[:files]` after updating the upload form to send `params[:csv]`. I prefer specifiying the file format because it helps separate from the other two attachment types we have: `files` and `images`.
=> fix the param name and callbacks

app/views/layouts/dashboard/_sidebar.html.erb
references https://github.com/rubyforgood/homeward-tails/issues/1337
Currently, the link to the Fosters section of the application is named "Fosters". 
Instead, we would like the link text to be "In Foster"
=> Change Link Name for Fosters Section on Sidenav

app/controllers/organizations/staff/pets_controller.rb
references https://github.com/rubyforgood/homeward-tails/issues/1335
Currently, when a staff creates a pet, the redirect behavior is as follows: 
Successful Creation -> Redirect to Index 
Unsuccessful Creation -> Redirect to New
However, this is not the behavior that we want. Instead, the redirect behavior should be as follows: 
Successful Creation -> Redirect to Show for Newly Created Pet
Unsuccessful Creation -> Redirect to Index and Flash Error 
I did not add controller tests for this change as advised in the ticket, but I am happy to do so if it would be beneficial! 
https://cassie.neetorecord.com/watch/072465a0442f283a16d7
=> Update Redirect Behavior Based on Success of Pet Creation

docker-compose.yml, dockerfile.dev, entrypoint.sh
Resolves #1334 
The queue and cable database's tables were not being created when initially running db:migrate. The default install of Solid Cable and Solid queue do not add a migration file. The tables are built from the schema files. Running db:migrate seems to looks for the migration files and when there is none, it overwrites the schema files and we end up with an database with no tables.
This change adds db:prepare to the entry point file which properly creates the tables and also seeds the db. I also removed asset precompile, maybe that will help with the assets issues in development?? #1317 
I'd suggest nuking your database, then run docker compose build.
=> Fix: docker databases

config/database.yml, docker-compose.yml
The sass service in docker was getting an error due to missing missing env variables. Updated accordingly.
I've also removed the `DATABASE_URL` variable. `ENV['DATABASE_URL']` is merged with and/or takes precedence over what is defined in `database.yml` ( [connection preference](https://guides.rubyonrails.org/configuring.html#connection-preference) ). 
Prior to #1353 , the primary database `postgres` was using `DATABASE_URL` to set the port and the db's `cable` and `queue` were using the default port 5432 from the postgres adapter. We are now explicitly defining ports etc. in `database.yml`  so I feel it make sense to keep in all on one place. This required adding a default host variable for docker to connect correctly.
=> Docker Compose Sass Error

.kamal/secrets, Dockerfile, config/database.yml, config/deploy.yml
Production deployment is [failing](https://github.com/rubyforgood/homeward-tails/actions/runs/13272488520/job/37054989476#step:7:9) after the recent env variable changes for the database connections. I've changed the Kamal secret variable names to match the naming convention used for the default db config. This should* work.
I also did a minor change to the kamal log alias we have defined. `kamal app logs` displays STDOUT but we are logging to production.log.
=> Deployment Failure Fix: Use default env var db names

Dockerfile, config/database.yml
I am unable to figure out where in the kamal deployment `bin/rails` is being run which causes the failure when the env variables are not set. 
The assets:precompile was one location which I was able to replicate locally and resolve. I was able to deploy to production from my machine successfully. However, somewhere in the deployment flow, my local `DATABASE_USERNAME` was being read. When I removed it, the deployment failed the same as from the github [action.](https://github.com/rubyforgood/homeward-tails/actions/runs/13285027555/job/37091740951#step:7:8)
Adding the default username and password back to `database.yml` is the simplest solution at this time and removes the need to add dummy values in multiple places. This also removes the risk of someone mistakenly updating a dummy value …
=> Add default db username and password back

db/seeds/01_alta.rb, db/seeds/02_baja.rb
#1365 
This eliminates the random broken pet images in development however it does not address the root cause. I created an issue which we might consider keeping open in case someone can address the real issue and/or we get the same issue in production when more data is being added.
Overall I still think this is a good change for the seed data. This creates a single blob from a single image file. Each pet then associates with that one blob. Currently we take the single `hero.jpg` image and create/upload a blob and new file on disk over and over again for each pet even though it is the same image. Of course this is not what we do in production per say, but I don't think we need 200 different dummy images just for seed data.
=> Development Image Errors: Attach same blob to each pet

app/controllers/organizations/staff/fosterers_controller.rb, app/models/concerns/exportable.rb, app/models/person.rb, app/views/organizations/staff/fosterers/index.html.erb, config/locales/en.yml, test/controllers/organizations/staff/fosterers_controller_test.rb
https://github.com/rubyforgood/homeward-tails/issues/1338
Adds a button allowing users to export fosterer emails, preserving search terms or filters on the manage fosters dashboard. Also adds tests for filters on manage fosters dashboard.
=> Export fosterer emails to CSV

app/views/organizations/adopter_fosterer/fostered_pets/index.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1091
Fosterers can view their fostered pets through the dashboard, and there is a card for each pet with their name and photo. 
However, it's not immediately clear when or for how long these pets were fostered (or are being fostered). It would be helpful to have this information visible at a glance, so we should add the start and end date to the foster's card. 
Current: 
After Date Range Addition: 
On Mobile:
=> Add Start and End Date to Foster Card - 1091

app/controllers/organizations/adopter_fosterer/fostered_pets_controller.rb, app/views/organizations/adopter_fosterer/fostered_pets/index.html.erb, test/controllers/organizations/adopter_fosterer/fostered_pets_controller_test.rb, test/factories/pets.rb
https://github.com/rubyforgood/homeward-tails/issues/1231
Fosterers can see a list of their current foster pets on the /fostered_pets index. However, it doesn't let fosterers view files or tasks of their upcoming fosters. 
This PR includes upcoming fosters in the query, and uses the badge from the staff fosters page. 
I tried a few different placements for the badge, and I feel that the best options are below the photo and above the dates. 
Badge Below Photo: 
Badge Above Dates: 
I felt like the badge below the photo felt a little more evenly distributed, so that's what I have in the PR now. However, I'm happy to change it to the badge above the dates if that would be preferable. 
Interestingly, the difference between these two options is only visible on large pages - as the page gets …
=> Include Upcoming Fosters on Fostered Pets Index - 1231

app/views/layouts/shared/_footer.html.erb, app/views/layouts/shared/_no_tenant_footer.html.erb
Remove script and update with <%= Time.now.year %> to get current year for copyright.
https://github.com/rubyforgood/homeward-tails/issues/1367
Remove script in partials where the copyright is. (layouts/shared/_footer and _no_tenant_footerand update) and update with <%= Time.now.year %> to get current year for copyright.
[(https://jam.dev/c/70877a41-a752-4986-a148-ea119a55e699)](https://jam.dev/c/70877a41-a752-4986-a148-ea119a55e699)
=> bug-fix: duplicating copy right year

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_google_oauth_button.html.erb, app/views/devise/shared/_links.html.erb
#1402
- Keeping it DRY and removing repetitive code by creating a devise partial for the google oauth button
- Move the google oauth button to respective location within registrations and sessions new views
- Removes google oauth button from devise shared links partial ("app/views/devise/shared/_links.html.erb")
<h3> Before </h3>
<h3> After </h3>
=> Relocate the Google Authentication

app/controllers/registrations_controller.rb
[Fix: Nav bar is removed when sign-up validation errors occur](https://github.com/rubyforgood/homeward-tails/issues/1423)
When a user signs up and a validation error occurs, the navbar remains visible
https://github.com/user-attachments/assets/a78c73a4-e3b5-4a53-b223-dc2e7ea9b2ea
=> Fix: Show Navbar when sign up validation error occurs

app/views/layouts/dashboard/_sidebar.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1427
Displayed Org Name and Logo Both in Staff Dashboard
https://github.com/user-attachments/assets/c3479aa6-146a-4c59-8d29-90532e31fa7b
=> Displayed Org Name and Logo Both in Staff Dashboard

Gemfile, Gemfile.lock, config/storage.yml
`ActiveStorage::Service::AzureStorageService` is deprecated and will be removed in Rails 8.1
This migrates from Azure-Storage-Blob to Azure-Blob
=> migrate to azure-blob gem

.tool-versions, lib/tasks/production_db.rake
This allows backing up the production database to your local machine and restoring it to the dev db. I have not tested this using docker.
This could be altered easily in the future to create the backup and store it in an azure blob. [Reference human-essentials bakup](https://github.com/rubyforgood/human-essentials/blob/main/lib/tasks/backup_db.rake) and [restore](https://github.com/rubyforgood/human-essentials/blob/main/lib/tasks/fetch_latest_db.rake). We currently rely on Azures built in db backup but I do not believe that we can access the actual dump file. Creating a backup blob would be an alternate/additional method. Something to discuss in the future.
=> Production db backup to local

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, config/locales/en.yml
Resolves #1465 
Adds powered by Homeward Tails links on sign_in/sign_up pages. Link opens global root page in a new tab.
I think having the link at the bottom of the card is unobtrusive and keeps the top of the form clean. Open to suggestions on styling/placement.
[Screencast from 2025-06-27 20-25-04.webm](https://github.com/user-attachments/assets/8f117a68-dc7e-47ed-bcf0-5f3113e0f5b7)
=> #1465 add powered by homeward tails links

app/controllers/organizations/staff/custom_pages_controller.rb, app/views/organizations/home/index.html.erb, app/views/organizations/staff/custom_pages/_form.html.erb, app/views/organizations/staff/custom_pages/edit.html.erb, config/locales/en.yml
Resolves #1468 
This adds links to the pages represented by the images. I added a darkening to the image on mouseover to give indication to the user. A confirmation is presented before navigating from the page. A tooltip was added below the `Additional Pet Information` section to advise the user that they must have at least one pet created to view it live. The same warning is show on the confirm dialog. If the user proceeds they are directed to the `staff/pets` page. If at least one unadopted pet is in the database, they are directed to the pet show page.
Form inputs were added to a card. I also removed unused code.  The image section was already being hidden on mobile so I kept that the same. I think that makes the most sense.
[Screencast from 2025-06-28 …
=> #1468 custom page links

app/views/organizations/staff/default_pet_tasks/_default_pet_tasks_table.html.erb, config/locales/en.yml
#1486 
-> Updated the Message For the Empty State.
=> 1486 - Refactor default pet tasks table to include empty state handling

app/controllers/static_pages_controller.rb, app/models/organization.rb, app/views/layouts/shared/_navbar.html.erb, app/views/static_pages/organizations.html.erb, db/migrate/20250712211752_add_active_column_to_organizations.rb, db/schema.rb, test/models/organization_test.rb
Adds active column to Org that is default to true. 
Also cleans up the static controller a bit. 
I also made the org top nav white because A) it's cleaner and B) logos are much easier to make look good on a white background.
@jmilljr24 if you have time could you set Baja and Petey to `active: false` in production please? Feel free to merge this if you are happy with it.
=> Add active to Org and small fixes

app/views/layouts/shared/_footer.html.erb, app/views/shared/_powered_by.html.erb, config/locales/en.yml
Just proposing re-designing the org footer a bit, and the powered by logo to just smush it a bit closer together. Style could be finessed at smallest width, but this is a movement to what I think it a slightly better layout in the footer. Thoughts?
Lg
Md
Sm
=> tweak org footer

app/views/organizations/staff/pets/_form.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1480
* Changes from date_select to date_field in order to improve both resposivity and UX (by using a single field instead of a select date group)
* Change the order of the two toggles at the bottom of the form so published is first
https://github.com/user-attachments/assets/f79ebe67-c08c-4e17-b451-5b07bf432843
=> refac: replace date_select with date_field and reorder application_paused checkbox

app/views/layouts/adopter_foster_dashboard.html.erb, app/views/organizations/adoptable_pets/show.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1531
Added background image to the pet show page header to match the adopter dashboard header as well as added the recommended padding-top to the header
=> 1531 - adding background image to header on pet show page

Gemfile, Gemfile.lock, app/components/dashboard_page_component.html.erb, app/components/dashboard_page_component.rb, app/components/nav_tab_component.html.erb, test/components/dashboard_page_component_test.rb
#1532 
- Upgraded view_component gem to its latest version 4.0.0
- Need to do some code changes as latest version does not call helpers directly on component instance so we need to explicitly specify it in code.
NA
=> Upgrade view_component gem to latest version 4.0.0

app/models/concerns/authorizable.rb
When a page is loaded, a persons permissions are checked for many elements on the page such as links. This causes a query for each permission to be checked. This change memoizes the permissions so we prevent multiple queries in a single request.
**Before**
**After**
=> Memoize permissions
