- .github/pull_request_template.md
- .github/workflows/rubyonrails.yml
> Add pull request template

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- Moving "contributing" guide to separate file
- Adding code of conduct
- Generifying README
#1
> Updating README

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/organization.rb
- app/models/pet.rb
- db/migrate/20230727210215_add_subdomain_to_organizations.rb
- db/schema.rb
- test/fixtures/organizations.yml
This adds the `acts_as_tenant` gem and makes minimal use of it on the `pet` model.
#5
> Add acts as tenant

- CONTRIBUTING.md
- README.md
- Remove "fork" instructions - contributors can submit PRs to this repo directly
- Update "dependencies/skills" section
#1
> Updating contribution doc and readme

- app/controllers/adopter_applications_controller.rb
- app/helpers/messages_helper.rb
- test/integration/adopter_application_test.rb
Adding affirmation list for onboardees to add to for first issue
#17
> Code change for creating an onboarding issue

- LICENCE
Sorry prematurely merged in a commit that didn't include the details in the licence file
> Add missing details in license

- README.md
- config/application.example.yml
Updates the README to move the setup instructions further to the top with some emojis (because why not!). Moreover, try to streamline the application.yml setup.
N/A
> Update the README to try to be more clear

- .tool-versions
https://github.com/rubyforgood/pet-rescue/blob/41bfb59ab26649b172b683a86a285785445d9465/README.md?plain=1#L45
> Add the postgres version to asdf as according to the old README.md

- Gemfile
- Gemfile.lock
- README.md
- db/seeds.rb
Added faker gem and utilized it in the creation of seed pets, and cleaned up seed users emails for readability
https://github.com/rubyforgood/pet-rescue/issues/30
> Modified pets seeds to utlize faker and cleaned up user emails 

- app/models/pet.rb
Just removing the uniqueness validation on Pet name
https://github.com/rubyforgood/pet-rescue/issues/46
> Remove uniqueness validation on Pet name

- .gitignore
> ignore RubyMine (JetBrains) IDE config folder

- db/seeds.rb
This PR adds a second organization to the seeds file. It also renames a few variables and removes some unnecessary comments in the seedfile, which can easily get out of date.
This also adds AdopterApplications to the seeds file.
#44
> Add a second organization to seeds

- CONTRIBUTING.md
This PR adds a norm to the CONTRIBUTING.md file whereby people will merge their own PRs.
> Adding some helpful stuff to CONTRIBUTING.md

- bin/setup
Includes seeding inside the bin/setup command via using db:setup instead of db:prepare
N/A
> Update setup script to include seeding

- config/database.yml
Taken from https://stackoverflow.com/questions/59089991/ruby-2-6-5-and-postgresql-pg-gem-segmentation-fault
> Add obscure incantation to fix the universe

- app/models/pet.rb
- app/models/staff_account.rb
Remove belongs to redundancy and add acts as tenant
#62
> Add acts as tenant remove belongs to association

- README.md
To make the developer experience a little better, the README now includes instructions on how to run Standard's auto-fix command
https://github.com/rubyforgood/pet-rescue/issues/50
> Update README to include `standard:fix` command

- db/seeds.rb
I took the lazy way out so feel free to add more interesting images but in principle this at least gets images to display from our seed pets! :D
#31
> Add images to pet seeds

- config/cable.yml
> Follow-up from db rename

- README.md
> Fix formatting on README

- README.md
Adds a link to the README to the tools access control google sheets
https://github.com/rubyforgood/pet-rescue/issues/80
> README: Add google sheets for tool access control

- Gemfile
- Gemfile.lock
- test/models/pet_test.rb
- test/models/user_test.rb
- test/test_helper.rb
Adds https://github.com/thoughtbot/shoulda-matchers which makes it really easy to generate common syntax for very common tests. This should help us add testing because it "SHOULD" be easier (catch the punn :)?)
N/A
> Improve ease of testing with shoulda /w some new model tests!

- Gemfile.lock
- app/controllers/checklist_templates_controller.rb
- app/helpers/checklist_templates_helper.rb
- app/models/checklist_template.rb
- app/views/checklist_templates/_checklist_template.html.erb
- app/views/checklist_templates/_checklist_template.json.jbuilder
- app/views/checklist_templates/_form.html.erb
- app/views/checklist_templates/edit.html.erb
- app/views/checklist_templates/index.html.erb
- app/views/checklist_templates/index.json.jbuilder
- app/views/checklist_templates/new.html.erb
- app/views/checklist_templates/show.html.erb
- app/views/checklist_templates/show.json.jbuilder
- config/routes.rb
- db/migrate/20230729134738_create_checklist_templates.rb
- db/migrate/20230729151957_create_checklist_templates.rb
- db/schema.rb
- test/controllers/checklist_templates_controller_test.rb
- test/fixtures/checklist_templates.yml
- test/models/checklist_template_test.rb
- test/system/checklist_templates_test.rb
> scaffold checklist template

- app/admin/dashboard.rb
- app/controllers/adoptable_pets_controller.rb
- app/controllers/matches_controller.rb
- app/controllers/successes_controller.rb
- app/models/adopter_account.rb
- app/models/match.rb
- app/models/pet.rb
- app/views/organization_pets/show.html.erb
- app/views/successes/index.html.erb
- config/routes.rb
- db/migrate/20230729174234_rename_adoption_to_match.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/matches.yml
- test/integration/adoptable_pets_index_test.rb
- test/integration/adoption_application_reviews_test.rb
- test/integration/google_maps_data_builder_service_object_test.rb
- test/integration/revoke_adoption_test.rb
- test/integration/successes_page_test.rb
- test/mailers/match_mailer_test.rb
- test/mailers/previews/match_mailer_preview.rb
- test/models/pet_test.rb
Renaming "Adoption" to "Match" since the described relationship could be adoption or fostering etc. 
Resolves #73
> Rename "adoption" to "match"

- app/views/static_pages/no_tenant.html.erb
- test/integration/navbar_test.rb
Fixes current broken tests that search for account_select path
> Fix: Updated references to Create Account link

- app/controllers/checklist_template_items_controller.rb
- app/helpers/checklist_template_items_helper.rb
- app/models/checklist_template.rb
- app/models/checklist_template_item.rb
- app/views/checklist_template_items/_checklist_template_item.html.erb
- app/views/checklist_template_items/_form.html.erb
- app/views/checklist_template_items/edit.html.erb
- app/views/checklist_template_items/index.html.erb
- app/views/checklist_template_items/new.html.erb
- app/views/checklist_template_items/show.html.erb
- config/routes.rb
- db/migrate/20230729182638_create_checklist_template_items.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/checklist_template_items_controller_test.rb
- test/fixtures/checklist_template_items.yml
- test/fixtures/checklist_templates.yml
- test/models/checklist_template_item_test.rb
- test/system/checklist_template_items_test.rb
> Scaffold Checklist Template Items

- app/assets/stylesheets/application.scss
- app/views/adoptable_pets/index.html.erb
Add that "ken burnzy" effect on hovering over pets.
https://jam.dev/c/23fa902d-cd2b-4d1e-93bb-6fbe770d2910
> Cute zoom in on pets when you hover

- config/routes.rb
> Replaced harcoded routes with resourceful ones

- app/models/match.rb
- test/models/checklist_template_item_test.rb
- test/models/checklist_template_test.rb
- test/models/contact_test.rb
- test/models/donation_test.rb
- test/models/location_test.rb
- test/models/match_test.rb
- test/models/organization_test.rb
Fixes #105
I've added some model tests on validations and relationships. I skipped models that I think we're going to remove like the `*_account` models.
#105
> Add model tests

- app/views/layouts/application.html.erb
Replace old repo reference with new repo
> Replace repo reference

- test/controllers/checklist_template_items_controller_test.rb
- test/factories.rb
- test/integration/adoptable_pet_show_test.rb
- test/integration/adopter_application_test.rb
- test/integration/adopter_applications_page_test.rb
This PR converts a few more tests off fixtures and into using FactoryBot. It also fixes a source of flakiness that I had put into the factories so THAT'S GOOD. :D
#126
> Transition more to factorybot

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/adoptable_pets/index.html.erb
- app/views/adoptable_pets/show.html.erb
- app/views/organization_pets/_form.html.erb
- app/views/organization_pets/edit.html.erb
- app/views/organization_pets/index.html.erb
- app/views/organization_pets/new.html.erb
- app/views/organization_pets/show.html.erb
- config/locales/en.yml
- test/integration/adoptable_pet_show_test.rb
- test/integration/adoptable_pets_index_test.rb
- test/integration/org_pets_test.rb
- test/test_helper.rb
Extracting hard-coded text into variables to allow for translations (in smaller commits for easier code-review).
Once translations are in, we can include `?locales=es` to see the translations.
In this PR
- rails i18n gem
- adoptable_pets
- organization_pets
Resolves #21
> Moving text to locales file

- .github/workflows/rubyonrails.yml
> Capitalize workflow name for consistency

- app/views/static_pages/donate.html.erb
> Remove unnecessary hyperlink on donate page

- app/controllers/contacts_controller.rb
- app/controllers/registrations_controller.rb
- app/mailers/contacts_mailer.rb
- app/mailers/sign_up_mailer.rb
- app/mailers/staff_application_notification_mailer.rb
- app/services/MultiTenantService.rb
- app/services/multi_tenant_service.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- test/integration/adopter_application_test.rb
- test/integration/contact_form_test.rb
- test/integration/user_account_test.rb
Replacing the hard-coded emails with configurable ones
Will follow-up with other email content in #150 
Resolves #119
> Configure email addresses

- app/controllers/organization_pets_controller.rb
- test/integration/org_pets_test.rb
- test/test_helper.rb
Modify adoptable_pets_show_test to use factory bot factories instead of old fixtures. All tests passing
Related to #126
> Factorybot tests

- app/controllers/registrations_controller.rb
Redirects the user to browse pets after the adopter profile has been created.
https://github.com/rubyforgood/pet-rescue/issues/98
> Redirect user to browse pets after adopter profile has been created.

- test/controllers/states_controller_test.rb
This is a hotfix for my last PR which broke `main`. Turns out I needed to convert ooonnnne more test!
> Convert StatesControllerTest to use factories

- app/models/adopter_profile.rb
- app/views/adopter_applications/index.erb
- app/views/adopter_profiles/_form.html.erb
- app/views/adopter_profiles/edit.html.erb
- app/views/adopter_profiles/new.html.erb
- app/views/adopter_profiles/show.html.erb
- app/views/sign_up_mailer/adopter_welcome_email.html.erb
- config/locales/en.yml
- test/integration/adopter_application_test.rb
Extracting text for 
- adopter_profiles
- adopter_applications
#21
> Extracting text

- config/environments/production.rb
- config/environments/staging.rb
- config/storage.yml
Set staging environment to use local disk storage. Azure is not set up with Heroku. Other changes don't make a meaningful difference but will hopefully clarify things.
> Some config changes that will hopefully fix Heroku deployment

- config/locales/en.yml
- Fix i18n yaml for reserved words
> Some fixes

- app/views/layouts/shared/_no_tenant_footer.html.erb
- app/views/root/index.html.erb
…looks more like the app could
A very quick edit of the root and non-tenant footer to make it look more like the application might look to help with dev purposes. More fine-tuning to be done after UX and design feedback.
https://github.com/rubyforgood/pet-rescue/issues/182
> Very basic root page UI update

- app/controllers/organizations/dashboard_controller.rb
- app/views/layouts/application.html.erb
- app/views/layouts/dashboard.html.erb
- app/views/organizations/dashboard/index.html.erb
Add GeeksUI components to the organization's dashboard! Navbar/header styling
Builds on #187
> Org dashboard styling

- app/views/layouts/dashboard.html.erb
- app/views/layouts/dashboard/_sidebar.html.erb
- app/views/layouts/shared/_head.html.erb
This PR fixes the issues we had with the sidebar installation. It turns out that when we copied the contents over from the inspector we were also copying over classes and changes that the simplebar library handles which caused things to not work. The way I fixed it was I went into the `src` folder in the downloaded geeks library and saw that the sidebar actually was much more bare then we had it.
N/A
> Address issues with sidebar rendering in Dashboard

- .github/pull_request_template.md
I think it is good to update the Pull Request Template now that we are getting more contributions. A few main things changed are:
- Update the wording to be "Description" which should be clear enough what is being asked
- Adds emojis because why not!?
- Ask for screenshot/demo in the pull request. This is going to make reviewing a lot more simple!
N/A
> Update Pull Request Template to be a bit more informative & concise

- app/views/layouts/dashboard.html.erb
- app/views/layouts/dashboard/_sidebar.html.erb
Update nav-bar styling to stick to the same position when scrolling dashboard content
https://github.com/rubyforgood/pet-rescue/assets/34173394/0acf82a4-a722-452b-9ba1-625d808c2310
> Sticky nav bar

- app/views/organizations/pets/index.html.erb
- config/locales/en.yml
#210 
Updating index page to match geekui styling
> Updating index page to match geekui styling

- app/views/organizations/pets/show.html.erb
#211 
Update pet show screen to match geeksui mock
> Update pet show screen to match geeksui mock

- app/controllers/application_controller.rb
- app/controllers/organizations/staff_controller.rb
- app/views/layouts/dashboard/_sidebar.html.erb
- app/views/organizations/pets/index.html.erb
- app/views/organizations/staff/index.html.erb
- config/locales/en.yml
#212 
- Add staff index page (admin only)
- Fixed "create pet" button
- Re-ordered nav bar based on role
> Adding staff index page

- app/views/adoptable_pets/index.html.erb
- app/views/partials/_pet_card.html.erb
Closes #37 
Created a partial for pet_card and updated the design
https://jam.dev/c/69379f1a-df52-4a00-a325-552a84e16e96
> Created a partial for pet_card and updated the design

- app/controllers/organizations/staff_controller.rb
- app/models/user.rb
- app/views/organizations/staff/_form.html.erb
- app/views/organizations/staff/index.html.erb
- app/views/organizations/staff/new.html.erb
- config/brakeman.ignore
- config/routes.rb
#168 
Page for adding new staff members
- Random password is generated and has to be reset using "forgot password"
- Terms of service agreement not required
> Form for adding staff

- app/mailers/staff_application_notification_mailer.rb
- app/views/staff_application_notification_mailer/new_adoption_application.html.erb
Closes #32 
Updated new_adoption_application.html.erb to include a link to the pet's show page in the dashboard and the org's sign_in page
https://us05web.zoom.us/clips/share/BHVzMDQgabAf2ic9c6lFChSWohiMb0EpaPW4lP_h8Evf6SkeGEE
> Updated links in the new adoption application mail erb template

- app/views/layouts/dashboard.html.erb
Fixes #227 
I added a link to user edit to the account dropdown. 
https://github.com/rubyforgood/pet-rescue/assets/96994176/1bb5b2ff-8855-4d9c-a616-5a74823cfe88
> Add link to user edit

- Gemfile
- Gemfile.lock
Resolves #[242](https://github.com/rubyforgood/pet-rescue/issues/242) 
This PR introduces the `nice_partials` gem to the project.
- Added `nice_partials` gem to the Gemfile
- ran bundle install
- ran test and all passed
> update with nice_partials gem

- app/views/layouts/dashboard.html.erb
N/A
Minor clean up to replace placeholder data from mock with user info
> Replacing placeholder data with user info

- app/views/organizations/adoption_application_reviews/edit.html.erb
N/A
Fixed path to editing application info
> fix path for application review

- app/views/adoptable_pets/show.html.erb
- app/views/organizations/pets/show.html.erb
- app/views/partials/_pet_card_bigger.erb
N/A
Formatting the adoptable_pet page to use geekui components - the info for a pet as seen by adopters and folks who are not logged in.
> Cleanup adoptable pet page

- app/views/adoptable_pets/show.html.erb
N/A
Fixing button alignment and path
> Fixing button alignment and path

- app/views/partials/_pet_card.html.erb
- test/factories.rb
- test/integration/adoptable_pets_index_test.rb
N/A
- Enabling adoptable_pets#index tests
> Enabling working tests for updated UIs

- app/controllers/organizations/dashboard_controller.rb
- app/views/organizations/dashboard/index.html.erb
#284  
I tracked down where the organization dashboard was being routed. It was present, but being routed through the index action. I updated the index action to use instance variables scoped to the current user, and imported and formatted the html associated with the desired template. Added in organization name, and personalized welcome message to the user. 
I am unsure what exactly we want in the card for the dashboard I think some more discussion might need to take place, but I'm happy to make any changes suggested :)
> Org dashboard

- README.md
quick fix of readme all contributors table to start a second row
> fix all contributors table

- Gemfile
- Gemfile.lock
- app/controllers/organizations/pets_controller.rb
- app/models/pet.rb
- app/views/organizations/pets/index.html.erb
- app/views/static_pages/home.html.erb
Fixes #303 
I added searching for pets by 
- name - text field, matches partially, case insensitive
- sex - select field
- species - select field
- adoption status - select field. 
I used ransack gem for this. 
https://github.com/rubyforgood/pet-rescue/assets/96994176/7ac96f1e-9a9c-46b1-9801-504e11beb808
> Improve pets search

- app/views/layouts/dashboard.html.erb
> Change user dropdown links

- README.md
#254 
Added a contributions section. This section has basic guide lines for contributing to Pet Rescue, including how to add someone as a contributor through a pr
> Add contributions section to readme

- .all-contributorsrc
Quick syntax fix. Cannot add new members until fixed.
> All contributors JSON - fix syntax

- .all-contributorsrc
- README.md
> bulk update all contributors

- Procfile
n/a
Trying to fix issue where assets are not loading in heroku staging instance
> adding procfile

- config/environments/staging.rb
Stylesheets are not loading properly in staging
[By default dartsass only adds application.scss](https://github.com/rails/dartsass-rails#configuring-builds). Adding feather css to see if it needs to be explicitly included.
> Attempt to fix stylsheets in staging

- Gemfile
Faker error on staging seed
adding faker for seeding staging env
> adding faker for seeding staging env

- app/views/organizations/tasks/destroy.turbo_stream.erb
- test/controllers/organizations/tasks_controller_test.rb
https://github.com/rubyforgood/pet-rescue/issues/422
Adding turbo_stream view to tasks/destroy.turbo_stream.erb and testing
https://github.com/rubyforgood/pet-rescue/assets/131488886/8a45b5c7-7a7d-48aa-bbbf-4329f18f7040
> 422 fix pet task delete

- app/models/adopter_profile.rb
- app/models/location.rb
- app/models/match.rb
- app/models/pet.rb
- config/locales/en.yml
- db/migrate/20231228081555_remove_pause_reason_from_pets.rb
#153 
Added internationalization to model validation error messages
> internationalized models validation error messages

- app/views/components/_attachment_form.html.erb
- config/locales/en.yml
> Updated design of image/file upload

- app/views/organizations/pets/tabs/_overview.html.erb
> UI updated

- app/views/organizations/pets/tabs/_applications.html.erb
This pr addressed #432  . I have updated the relevant code and removed the redundant pet name from applications tab.
> Remove redundant pet name

- Gemfile
- Gemfile.lock
- app/controllers/concerns/organization_scopable.rb
- app/controllers/organizations/default_pet_tasks_controller.rb
- app/views/organizations/default_pet_tasks/_form.html.erb
- app/views/organizations/default_pet_tasks/edit.html.erb
- app/views/organizations/default_pet_tasks/index.html.erb
- app/views/organizations/default_pet_tasks/new.html.erb
- app/views/organizations/pets/_form.html.erb
- app/views/organizations/pets/tasks/_tasks.html.erb
- config/locales/en.yml
- test/controllers/organizations/default_pet_tasks_controller_test.rb
[Issue 395](https://github.com/rubyforgood/pet-rescue/issues/395)
Add CRUD actions for Default Pet Tasks.
https://github.com/rubyforgood/pet-rescue/assets/33605808/3e591bd9-a975-4bb0-b0b1-2bfce93f480a
> [#395] Staff can CRUD Default Pet Tasks

- Procfile
Running into issues auto deploying code but not running migrations
Updating procfile to include db migrations
> Auto-migrate on deploys to heroku

- app/views/organizations/pets/tasks/_tasks.html.erb
This pr addressed #453 . I have updated the relevant code and changed the design & position of new task button.
> Change design & position of new task button

- .github/workflows/codeql.yml
- .github/workflows/rubyonrails.yml
- .gitignore
- git ignore local .env file
- update action version to handle deprecated node version (16 -> 20)
> Updates and cleanup 🤏 

- app/views/organizations/pets/index.html.erb
- app/views/organizations/pets/tabs/_overview.html.erb
- config/locales/en.yml
> Fix: message property 🤏 

- app/controllers/errors_controller.rb
- app/views/errors/unprocessable_content.html.erb
- config/routes.rb
#534 
This error code seems like it was incorrectly named at some point.
https://developer.mozilla.org/en-US/docs/web/http/status/422
> Change 422 to correct status name, Unprocessable Content

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- test/integration/adoptable_pet_show_test.rb
- test/integration/adoption_application_reviews_test.rb
Re-adding integration tests for review applications view and other test cleanup
> Re-adding integration tests for review applications view

- app/views/organizations/adoptable_pets/show.html.erb
fixes https://github.com/rubyforgood/pet-rescue/issues/656
https://github.com/rubyforgood/pet-rescue/assets/55315065/26e045f7-f567-43ff-bf83-77e252b6c8fc
https://github.com/rubyforgood/pet-rescue/assets/55315065/cd2b97e0-c319-422a-ab03-f28887a2be86
> Manually deleted the profile for testing ```complete your profile flow```
> fix: Fosterers cannot apply for pets

- app/controllers/organizations/staff/invitations_controller.rb
- test/controllers/organizations/staff/invitations_controller_test.rb
#695 
Have raised exception for unused invitations controller #new action and updated test to validate it.
NA
> Raise an error if a developer tries to use the #new action in the invitations controller

- app/views/organizations/staff/pets/index.html.erb
- Removed unnecessary columns from pets#index
> Removed unnecessary columns from pets#index

- app/controllers/organizations/staff/adoption_application_reviews_controller.rb
- app/models/adopter_application.rb
- app/views/organizations/staff/adoption_application_reviews/index.html.erb
- db/seeds/01_alta.rb
- db/seeds/02_baja.rb
- test/integration/adoption_application_reviews_test.rb
-   Fixed bug in alta and baja seed data 
-   Added pagination to adoption application reviews and fixes failed test
> 706 add pagination adoption application reviews

- app/controllers/concerns/organization_scopable.rb
- app/controllers/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/organizations/staff/organization_profiles/_form.html.erb
Places devise registration and session forms in the appropriate layouts and redirects new sign ups (adopters) to the dashboard.
https://www.loom.com/share/36610f27c3b649769a964a9ee28fc654?sid=08fb66b4-0e7e-4a9e-be27-52caa33f4362
> Place Devise forms in appropriate layouts and update redirects

- app/views/organizations/staff/adoption_application_reviews/index.html.erb
- app/views/organizations/staff/pets/index.html.erb
#749 
Adds pagy links to top of two views that implemented pagination already.
This completes this miro task: https://miro.com/app/board/uXjVMtlcmAI=/?moveToWidget=3458764589827405892&cot=14.
> Add pagination links to top of app reviews and staff pets views

- README.md
https://github.com/rubyforgood/pet-rescue/issues/756
I added a link to the Geek UI documentation to the useful links section of the readme
> Geek UI docs

- app/views/organizations/adopter_fosterer/dashboard/index.html.erb
https://github.com/rubyforgood/pet-rescue/issues/769
Added alert with link to complete adopter's profile
> 769 Adopters informed

- app/views/organizations/adoptable_pets/show.html.erb
#789 
PR merged to main causing failure due to incorrect translation path from a previous pr.
Path updated
> Fix translation path

- app/views/organizations/staff/tasks/_task.html.erb
- app/views/organizations/staff/tasks/index.html.erb
- config/locales/en.yml
https://github.com/rubyforgood/pet-rescue/issues/820
Adds recurring icon and label + translations related to the view.
> 820 Add recurring label to recurring tasks

- README.md
- docker-compose.yml
- dockerfile
- entrypoint.sh
Dockerizing the app to help lower the barrier to getting up and running for contributors. I opted to just use a dockerfile with docker-compose and rely on docker commands to get up and running - not using a devcontainer for now (I do not use VSCode).
With these changes so far, the app works as expected in Docker. However:
- System tests are failing still. I added Chromium to the base image, but now getting a ferrum timeout error. 
- I was having asset delivery issues, so I run the command to precompile assets, though I know this can slow boot times down a bit
- What would be ideal to include in a dockerignore file?
> Dockerize Pet Rescue

- doc/architecture/003-checklists.md
#807
Forgot to commit this change based on one of Ben's comments.
> Add comment about Task serving as Assignment

- config/database.yml
https://github.com/rubyforgood/pet-rescue/issues/894
Database Port config is modified to accommodate wsl environment
> Modified default database port config to work for wsl

- Gemfile
- Gemfile.lock
- config/initializers/strong_migrations.rb
Resolves https://github.com/rubyforgood/pet-rescue/issues/874
Added strong_migrations gem
> 874 Add strong_migrations gem

- Gemfile
Follow up of #874 
Moving gem to be used in all environment
> moving gem to global scope

- app/controllers/organizations/staff/adoption_application_reviews_controller.rb
- app/controllers/organizations/staff/dashboard_controller.rb
- app/models/pet.rb
- app/views/organizations/staff/dashboard/index.html.erb
#927
Swap pets tile with the Applicant tile on the Staff Dashboard
Added count for Under Review and Awaiting Review
[Screencast from 2024-09-01 16-53-15.webm](https://github.com/user-attachments/assets/b729d63c-6bc2-4e7e-9e76-2e512ccc4dd2)
> 927 Swap Pets tile with Applicants tile on the Staff Dashboard

- app/views/organizations/staff/adoption_application_reviews/index.html.erb
- app/views/organizations/staff/default_pet_tasks/index.html.erb
- app/views/organizations/staff/manage_fosters/index.html.erb
#928 
Fix Manage Fosters, Default Pet Task, and Adoption Application Review Layout to full width
[Screencast from 2024-09-01 17-48-41.webm](https://github.com/user-attachments/assets/ba1e6fee-d2d6-4d14-a6e0-90f4be15d5ff)
> 928 Fix Manage Fosters, Default Pet Task, and Adoption Application Review to full width

- app/components/pet_avatar_component.rb
- app/views/organizations/adopter_fosterer/likes/index.html.erb
#953 
Fix the bug preventing liked pets from rendering on the adopter/foster dashboard
https://github.com/user-attachments/assets/c44b2d11-b79b-4570-95bd-c55a4cf689fe
> 953 - Remove unused arguments from the Class object

- app/views/organizations/staff/pets/tabs/_applications.html.erb
#952 
Fixes UI Alignment in Adopter-Application-Review
https://github.com/user-attachments/assets/b1a4bbc3-d289-4bf9-9c90-fe316a5186d9
> 952 - Fixes UI Alignment in Adopter-Application-Review

- app/views/organizations/adopter_fosterer/adopter_applications/_applications_table.html.erb
- app/views/organizations/adopter_fosterer/likes/index.html.erb
- config/locales/en.yml
#955 
As per the issue
[Screencast from 2024-09-10 00-41-43.webm](https://github.com/user-attachments/assets/7e8a50d5-9bec-4cb3-bfee-37a2624988d6)
> 955 - Added condition to handle null state

- app/views/layouts/adopter_foster_dashboard.html.erb
- app/views/layouts/dashboard/_sidebar.html.erb
https://github.com/rubyforgood/pet-rescue/issues/968
Add a feedback button to the staff and adopter logged area.
> 968 - Add feedback link to dashboards

- app/helpers/pets_helper.rb
- app/models/match.rb
- app/models/pet.rb
- app/views/organizations/adoptable_pets/index.html.erb
- app/views/organizations/staff/pets/_pet_cards.html.erb
- app/views/organizations/staff/pets/_pet_table.html.erb
- app/views/organizations/staff/pets/show.html.erb
https://github.com/rubyforgood/pet-rescue/issues/970
This PR aims to include a badge according to the pet’s status
> add pet status badges

- app/components/pet_avatar_component.rb
https://github.com/rubyforgood/pet-rescue/issues/976
Remove purple border from PetAvatar
> remove purple border

- app/views/organizations/staff/adoption_application_reviews/index.html.erb
- app/views/organizations/staff/custom_pages/edit.html.erb
- app/views/organizations/staff/organizations/edit.html.erb
- config/breadcrumbs.rb
> 985 - Added The Breadcrumbs and Remove the SubTitle

- app/views/organizations/staff/adopters/_adopter_table.html.erb
- app/views/organizations/staff/fosterers/_fosterer_table.html.erb
- app/views/organizations/staff/staff/_staff_table.html.erb
#986 
Added space between avatar and name
> Fix issue #986

- app/views/organizations/staff/adopters/_adopter_table.html.erb
- app/views/organizations/staff/adoption_application_reviews/edit.html.erb
- app/views/organizations/staff/custom_form/forms/index.html.erb
- app/views/organizations/staff/custom_form/forms/show.html.erb
- app/views/organizations/staff/dashboard/_pets_with_incomplete_or_overdue_tasks.html.erb
- app/views/organizations/staff/dashboard/index.html.erb
- app/views/organizations/staff/default_pet_tasks/_default_pet_tasks_table.html.erb
- app/views/organizations/staff/default_pet_tasks/_form.html.erb
- app/views/organizations/staff/default_pet_tasks/index.html.erb
- app/views/organizations/staff/faqs/_faq.html.erb
- app/views/organizations/staff/fosterer_invitations/_form.html.erb
- app/views/organizations/staff/fosterer_invitations/new.html.erb
- app/views/organizations/staff/fosterers/_fosterer_table.html.erb
- app/views/organizations/staff/fosterers/index.html.erb
- app/views/organizations/staff/manage_fosters/_date_edit.html.erb
- app/views/organizations/staff/manage_fosters/_form.html.erb
- app/views/organizations/staff/manage_fosters/_foster_cards.html.erb
- app/views/organizations/staff/manage_fosters/_foster_table_row.html.erb
- app/views/organizations/staff/pets/tabs/partials/_application_create_button.html.erb
- app/views/organizations/staff/pets/tabs/partials/_foster.html.erb
- app/views/organizations/staff/staff/_staff_cards.html.erb
- app/views/organizations/staff/staff/_staff_table.html.erb
- app/views/organizations/staff/staff/index.html.erb
- app/views/organizations/staff/tasks/_form.html.erb
- app/views/organizations/staff/tasks/_task.html.erb
- app/views/organizations/staff/tasks/_tasks_toggle.html.erb
- config/locales/en.yml
https://github.com/rubyforgood/pet-rescue/issues/983
Move text about Organizations::Staff module to translate file
> staff view translation

- app/views/layouts/adopter_foster_dashboard.html.erb
https://github.com/rubyforgood/pet-rescue/issues/1001
Remove sample button
> remove sample button

- app/views/organizations/home/index.html.erb
Issue 994: buttons for creating an account and viewing adoptable 
#994 
Added button to main for an unauthenticated user to see a link to "Become an Adopter" and a button for an authenticated user to see a link to "Adopt a Pet"
> Issue 994: buttons for creating an account and viewing adoptable 

- app/views/organizations/adopter_fosterer/likes/index.html.erb
If you sign in as an adopter and like a pet then try to go to your dash to view liked pets you will see an error. This fixes it.
> fixes adopter liked pets bug

- db/seeds/01_alta.rb
- db/seeds/02_baja.rb
> Fix seed file match creation

- app/views/organizations/home/index.html.erb
#1018 
Remove PAGE HIGHLIGHTS section from organizational root page
> 1018 Org Root Page remove the additional links section

- app/views/layouts/dashboard/_sidebar.html.erb
#1017
Change the icon of `Custom Page` menu in the sidebar to `fe-layout`
> 1017 Change Custom Page icon to fe-layout in the sidebar

- app/models/adopter_application.rb
- config/locales/en.yml
- db/migrate/20241004082759_add_unique_constraint_to_adopter_application.rb
- db/schema.rb
- test/models/adopter_application_test.rb
> #1024: Add unique constraint and model validation to AdopterApplication

- db/seeds/01_alta.rb
- db/seeds/02_baja.rb
Add random sampling to seeds for pet placement type and species
> update placement type and species to be random in seeds

- app/controllers/organizations/staff/external_form_upload_controller.rb
- test/controllers/organizations/staff/external_form_upload_controller_test.rb
Resolves #1092 
Fix error with file param and update tests.
Side note. We should add some sort of notice to the user after the file has been submitted. There is no redirect or notice after uploading.
> #1092 Fix file param for CSV upload

- app/views/organizations/staff/custom_pages/_form.html.erb
#990 
Left out small chore from the last PR #993 , didn't knew how to place commit on same PR.
> chore: update border color of images

- README.md
- docker-compose.yml
After merging the changes for deploying to Azure a couple things broke in docker...or maybe it exposed a couple of deficiencies in the docker setup :) either way, this PR fixes them.
> Fix docker setup

- app/views/organizations/adopter_fosterer/dashboard/index.html.erb
This update improves the responsive design of the dashboard page (app/views/organizations/adopter_fosterer/dashboard/index.html.erb) by adjusting button and image spacing. The following changes were made:
Added mt-sm-2 and mt-1 classes to the buttons to ensure they wrap correctly on tablet screens and have consistent spacing.
Reduced the top margin on the image element from mt-12 to mt-6 to minimize excess spacing on tablet and mobile views, improving the overall visual balance on smaller screens.
These adjustments enhance readability and layout consistency across different devices.
> Enhance Responsive Layout for Buttons and Image on Dashboard Page

- .github/workflows/kamaldeploy.yml
> Workflow deploy weekly

- app/views/organizations/home/index.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1122
Replaced the text for organization home page from "Complete Profile" to "Complete Questionnaire".
> update step 2 copy on org home

- app/views/root/index.html.erb
- config/locales/en.yml
[https://github.com/rubyforgood/homeward-tails/issues/1143](url)
The issue described was an increase in size for the 3 headings and 3 paragraphs within the section element "bg-white py-4 shadow-sm" on lines 32-61 of app/views/root/index.html.erb. As well as a change to the actual text in some of the paragraphs and one of the headings.
I used the bootstrap utilities to adjust the headings as the custom.scss file asked me to use the utilities over creating my own custom css so as to keep to the same styles. I added in the fs- utilities to the h4 elements giving them the values of fs-2 putting the headers at 2.5rem for font size. I find this to be too big, but found that fs-3 would set it to 1.25rem which was much too small. Adding fs to the paragraph elements proved fruitless as fs-5 had …
> 1143 make section content larger

- app/views/layouts/shared/_no_tenant_navbar.html.erb
- app/views/organization_account_requests/new.html.erb
- config/locales/en.yml
#1160
removed the button, changed the text for the header and description and adjusted the CSS for the description slightly to better reflect the new changes
> #1160 Changed organization account request form

- app/views/organization_account_requests/new.html.erb
- config/locales/en.yml
Very quick change to make the title shorter and make the description paragraph the same width as the form for aesthetics
> Org account request: Update copy and copy width

- app/views/organizations/home/index.html.erb
#1168 
[Screencast from 2024-11-30 19-20-19.webm](https://github.com/user-attachments/assets/937d3756-339a-4e68-97e4-0e5b01938e58)
> #1168-added simple format to display paragraph

- config/locales/en.yml
#1191 
Added Transaltion
[Screencast from 2024-11-30 19-36-20.webm](https://github.com/user-attachments/assets/284cbcbb-d4ca-4f1e-8613-a7a30956eaba)
> #1191 added missing translation

- app/views/organizations/staff/tasks/_task.html.erb
- app/views/organizations/staff/tasks/index.html.erb
#1193 
[Screencast from 2024-11-30 21-20-35.webm](https://github.com/user-attachments/assets/9c67d991-3239-4957-b677-0972fdf6549d)
> #1193-style the view as per mobile

- app/views/organizations/home/index.html.erb
- config/locales/en.yml
#1192 
Introduce Grid for working in mobile tablet and desktop
[as.webm](https://github.com/user-attachments/assets/f8e613c0-e544-4b75-8702-44da9e63f91d)
> #1192 fix the ui for mobile

- app/controllers/organizations/staff/external_form_upload_controller.rb
- app/services/organizations/importers/csv_import_service.rb
- test/controllers/organizations/staff/external_form_upload_controller_test.rb
- test/services/organizations/csv_import_service_test.rb
Resolves #1243 
I decided remove the name "google" from the service. Testing is based off of a google form but the service should work with other csv forms as long as the headers for "Email" and "Timestamp" match.
> 1242 csv form submission

- config/initializers/bugsnag.rb
Fixes pipeline error when bumping standard: https://github.com/rubyforgood/homeward-tails/pull/1240
> avoid hard coding the path to dev null - it raises a standard error

- config/environments/production.rb
We lost log/production.log and I think this is why
> Remove logging to STDOUT so we log to production.log instead

- config/routes.rb
Accidentally duplicated the people > form submission block in the routes. This removes the duplicate.
> Remove duplicate block

- app/views/devise/registrations/new.html.erb
N/A
Fixes a few redundant things on the user sign up form for adopters.
> Fix sign up form

- app/views/organizations/staff/fosterers/_fosterer_cards.html.erb
* Removed joined date and added phone number, email and edit button
https://github.com/rubyforgood/homeward-tails/issues/1249
https://github.com/rubyforgood/homeward-tails/issues/1249
> 1249 - Update fosterer card details

- app/views/organizations/staff/pets/tabs/_applications.html.erb
[Original issue](https://github.com/rubyforgood/homeward-tails/issues/1336)
- Adds avatar `PetAvatarComponent` to adopter applications view.
_With image_
_Without image_
> Issue #1336: Add pet avatar to adopter applications

- .github/workflows/rubyonrails.yml
n/a
This updates the workflow environment variables to be consistent with changes in #1353. This needs to be merged before #1353 can pass the workflows. 
n/a
> Update gh workflow env variables

- app/views/organizations/staff/fosterers/_fosterer_cards.html.erb
> fix no method error

- .github/workflows/rubyonrails.yml
- bin/style
n/a
This uses bundler to run standard in the Github action instead.
n/a
> Update standard runner

- Dockerfile
This was causing the build to fail. The previous changes made are fine to keep.
> Add dummy variables for production assets precompile

- app/assets/stylesheets/application.scss
https://github.com/rubyforgood/homeward-tails/issues/1374
Ran the sass-migrator to use the module system instead of the deprecated import system.
> Migrate sass to use module system

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/shared/_footer.html.erb
- app/views/layouts/shared/_no_tenant_footer.html.erb
- app/views/shared/_powered_by.html.erb
Resolves #1471 
This moved the powered by Homeward Tails link to an partials. The link is added to the root and org scoped footers. Minor adjusted to UI.
> 1471 create powered by partial

- config/locales/en.yml
https://github.com/rubyforgood/homeward-tails/issues/1476
- Updated the Hero Text
> 1476 - Update Hero Text

- app/views/organizations/staff/pets/tabs/partials/_application_info_card.html.erb
- app/views/organizations/staff/pets/tabs/partials/_application_info_table_row.html.erb
https://github.com/rubyforgood/homeward-tails/issues/1467
1. Update link to person form submissions in application info card
[Screencast from 15-07-25 12:41:53 AM IST.webm](https://github.com/user-attachments/assets/bda10367-20d3-4ef8-a02d-cb428df3c7a1)
> 1467 - Adopter Application Form Submission link broke on mobile

- app/views/organizations/staff/pets/tabs/partials/_foster_cards.html.erb
- app/views/organizations/staff/pets/tabs/partials/_foster_table.html.erb
Closes https://github.com/rubyforgood/homeward-tails/issues/1484
Mobile view
Desktop view
> feat: display info when there are no fosters

- config/locales/en.yml
#1530 
1. Correct typo in learn_more_about_description in English locale
> 1530 - Fix Global Root Page
